language: node_js
node_js:
  - "10"

cache: npm

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      if: branch = master
      before_script: gem install sass
      script: npm run build
      deploy:
        provider: pages
        local_dir: site
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          branch: master
