'use strict';

var R6MapsLangTermsMongolian = (function(R6MapsLangTerms, undefined) {
  var name = 'mn',
    terms = {
      general: {
        pageTitleSelectMap: 'R6Maps.com - Газар сонго',
        pageTitleStart: 'R6Maps.com',
        cameraViewCaption: '{floorName} камерын дүрс',
        shortcutTip: 'Shortcut: {shortcut}',
        menu: 'Цэс',
        about: 'Танилцуулга',
        languageHeader: 'Хэл',
        optionsHeader: 'Тохируулга',
        labelLosOpacity: 'Camera line-of-sight opacity',
        labelLosDefault: '(Анхны утга)',
        labelLos105: '(Айн?)',
        labelLos110: '(Дэндүү!)',
        labelRoomLabelStyle: 'Өрөөний нэрийн загвар',
        labelNumberFloorsToDisplay: 'Харуулах давхарын тоо',
        lockPanning: 'Гүйлтийг цоожлох',
        lockZooming: 'Томролтыг цоожлох',
        fullScreen: 'Дэлгэц дүүрэн',
        enableScreenshots: 'Зураг авах боломж',
        contributions: 'Хандив',
        supportSiteNote: 'Бага зэргийн хандив өргөн намайг дэмжихийг хүсье. :)',
        donateImg: 'https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif',
        latestUpdate: '2017 оны 2 сарын шинэчлэл',
      },
      sessions: {
        button: 'Sessions (BETA)'
      },
      roomLabelStyles: {
        Dark: 'Бараан',
        Light: 'Цайвар (анхны утга)',
        DarkAndLarge: 'Том, бараан',
        LightAndLarge: 'Том, цайвар',
        DarkAndSmall: 'Жижиг, бараан',
        LightAndSmall: 'Жижиг, цайвар',
        DisplayNone: 'Унтраах'
      },
      floorDisplayOptions: {
        one: '1 - Дан',
        two: '2 - Зэрэгцээ',
        four: '4 - Дөрвөлжин'
      },
      selectMaps: {
        selectAMap: 'Газар сонго',
        homeLink: 'Газар сонго'
      },
      compass: {
        letterN: 'Х',
        letterE: 'З',
        letterS: 'Ө',
        letterW: 'Б'
      },
      floorNames: {
        basement: { full: 'Суурь', short: 'С' },
        firstFloor: { full: '1-р давхар', short: '1' },
        secondFloor: { full: '2-р давхар', short: '2' },
        thirdFloor: { full: '3-р давхар', short: '3' },
        fourthFloor: { full: '4-р давхар', short: '4' },
        roof: { full: 'Дээвэр', short: 'Д' }
      },
      objectives: {
        bombShortA: 'A',
        bombShortB: 'B',
        bomb: 'Бөмбөг',
        hostageShort: 'H',
        hostage: 'Барьцаа',
        secureShort: 'S',
        secure: 'Эзлэх',
        showAll: 'Бүгдийг харуул'
      },
      legend: {
        breakableWalls: 'Эвдэрдэг хана',
        breakableFloorTraps: 'Эвдэрдэг шалны хаалга',
        ceilingHatches: 'Таазны хаалга',
        lineOfSightWalls: 'Нэвт буудаж болох хана',
        lineOfSightFloors: 'Нэвт буудаж болох шал',
        droneTunnels: 'Дроны хонгил',
        objectives: 'Бай',
        insertionPoints: 'Эхлэлийн цэг',
        securityCameras: 'Аюулгүй байдлын камер',
        skylights: 'Таазны цонх',
        onFloorAboveOrBelow: 'Дээд эсвэл доод давхарт',
        cameraLineOfSight: 'Камерын харах өнцөг',
        ladders: 'Авирдаг шат'
      },
      spawnPoints: {
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        e: 'E'
      },
      mapNames: {
        bank: 'Банк',
        bartlett: 'Бартлетт И.С.',
        border: 'Хил',
        chalet: 'Дүнзэн байшин',
        club: 'Клубын байр',
        consulate: 'Консулын газар',
        coastline: 'Далайн эрэг',
        favela: 'Фавела',
        hereford: 'Херфорд',
        house: 'Байшин',
        kanal: 'Суваг',
        kafe: 'Достоевский кафе',
        oregon: 'Орегон',
        plane: 'Онгоц',
        skyscraper: 'Өндөр байшин',
        yacht: 'Дарвуулт хөлөг'
      },
      mapRooms: {
        bank: {
          spawnBoulevard: 'Boulevard',
          spawnBackAlley: 'Back Alley',
          printerRoom: 'Printer Room',
          parkingLot: 'Parking Lot',
          boulevard: 'Boulevard',
          jewelryFront: 'Jewelry Front',
          plaza: 'Plaza',
          mainEntrance: 'Main Entrance',
          garageRamp: 'Garage<br/>Ramp',
          exteriorParking: 'Exterior Parking',
          garageRoof: 'Garage<br/>Roof',
          alleyAccess: 'Alley Access',
          backAlleyRooftop: 'Back Alley<br/>Rooftop',
          backAlley: 'Back Alley',
          highRoof: 'High Roof',
          lowRoof: 'Low Roof',
          vault: 'Vault',
          goldVault: 'Gold<br/>Vault',
          serverRoomStairs: 'Server Room Stairs',
          serverRoom: 'Server Room',
          CCTVRoom: 'CCTV<br/>Room',
          loadingDock: 'Loading Dock',
          secureHallway: 'Secure<br/>Hallway',
          sewer: 'Sewer',
          lockers: 'Lockers',
          vaultLobby: 'Vault Lobby',
          vaultEntrance: 'Vault<br/>Entrance',
          mainStairway: 'Main<br/>Stairway',
          bankGarage: 'Bank Garage',
          elevators: 'Elevators',
          tellersOffice: 'Tellers\'<br/>Office',
          archives: 'Archives',
          tellers: 'Tellers',
          loanOffice: 'Loan Office',
          officeHallway: 'Office Hallway',
          skylightStairwell: 'Skylight<br/>Stairwell',
          lobby: 'Lobby',
          openArea: 'Open Area',
          staffRoom: 'Staff Room',
          electricalRoom: 'Electrical<br/>Room',
          adminOffice: 'Admin Office',
          ATMs: 'ATMs',
          executiveHallway: 'Executive<br/>Hallway',
          frontDesk: 'Front<br/>Desk',
          executiveLounge: 'Executive<br/>Lounge',
          CEOOffice: 'CEO<br/>Office',
          janitorCloset: 'Janitor Closet',
          hallway: 'Hallway',
          terrace: 'Terrace',
          stockTradingRoom: 'Stock<br/>Trading<br/>Room',
          conferenceRoom: 'Conference<br/>Room'
        },
        bartlett: {
          archwayHall: 'Archway Hall',
          archwaylHallway: 'Archway Hallway',
          backAlley: 'Back Alley',
          bathroom: 'Bath-<br/>room',
          campusField: 'Campus<br/>Field',
          classroom: 'Classroom',
          coatRoom: 'Coat<br/>Room',
          compassHallway: 'Compass Hallway',
          courtyard: 'Courtyard',
          centralHallway: 'Central<br/>Hallway',
          diningRoom: 'Dining Room',
          eastBalcony: 'East Balcony<br/>(not shown)',
          eastCorridor: 'East<br/>Corridor',
          eastStairs: 'East<br/>Stairs',
          festival: 'Festival',
          frontEntrance: 'Front Entrance',
          frontOffice: 'Front<br/>Office',
          frontPatio: 'Front Patio',
          gardenPass: 'Garden<br/>Pass',
          kitchen: 'Kitchen',
          lobby: 'Lobby',
          lounge: 'Lounge',
          lowerLibrary: 'Lower<br/>Library',
          mainGate: 'Main<br/>Gate',
          mainOffice: 'Main Office',
          modelHall: 'Model Hall',
          pantry: 'Pantry',
          parking: 'Parking',
          pianoRoom: 'Piano Room',
          readingRoom: 'Reading Room',
          roof: 'Roof',
          rowingMuseum: 'Rowing<br/>Museum',
          serviceRoom: 'Service<br/>Room',
          terrace: 'Terrace',
          trophyRoom: 'Trophy<br/>Room',
          upperLibrary: 'Upper<br/>Library',
          vistaHallway: 'Vista<br/>Hallway',
          westBalcony: 'West Balcony<br/>(not shown)',
          westCorridor: 'West<br/>Corridor'
        },
        border: {
          armoryLockers: 'Armory<br/>Lockers',
          tellers: 'Tellers',
          ventilationRoom: 'Venti-<br/>lation<br/>Room',
          exitHallway: 'Exit<br/>Hallway',
          supplyCorridor: 'Supply<br/>Corridor',
          detention: 'Detention',
          customsInspection: 'Customs Inspection',
          customsDesk: 'Customs<br/>Desk',
          centralStairs: 'Central Stairs',
          serverRoom: 'Server Room',
          supplyRoom: 'Supply Room',
          workshop: 'Work-<br/>shop',
          mainLobby: 'Main<br/>Lobby',
          bathroom: 'Bath-<br/>room',
          waitingRoom: 'Waiting<br/>Room',
          eastStairs: 'East<br/>Stairs',
          passportCheck: 'Passport<br/>Check',
          archives: 'Archives',
          offices: 'Offices',
          officesHallway: 'Offices Hallway',
          fountain: 'Fountain',
          mainHallway: 'Main<br/>Hallway',
          armoryDesk: 'Armory<br/>Desk',
          securityRoom: 'Security<br/>Room',
          breakRoom: 'Break Room',
          spawnEastVehicleEntrance: 'East Vehicle Entrance',
          spawnValley: 'Valley',
          spawnWestVehicleExit: 'West Vehicle Exit',
          westTower: 'West<br/>Tower',
          pedestrianExit: 'Pedestrian Exit',
          valley: 'Valley',
          parkingLotEntrance: 'Parking Lot<br/>Entrance',
          parkingLot: 'Parking Lot',
          westRoad: 'West Road',
          vehicleCustoms: 'Vehicle Customs',
          crashScene: 'Crash Scene',
          eastRoad: 'East Road',
          pedestrianEntrance: 'Pedestrian<br/>Entrance',
          pedestrianCustoms: 'Pedestrian<br/>Customs',
          watchTower: 'Watch<br/>Tower',
          eastAlley: 'East Alley',
          parkingLotAlley: 'Parking<br/>Lot<br/>Alley',
          northBalcony: 'North Balcony',
          eastBalcony: 'East<br/>Balcony',
          westBalcony: 'West<br/>Balcony',
          southBalcony: 'South Balcony',
          roof: 'Roof'
        },
        chalet: {
          spawnFrontYard: 'Front Yard',
          spawnCampfire: 'Campfire',
          spawnCliffside: 'Cliffside',
          spawnLakeside: 'Lakeside',
          libraryStairs: 'Library<br/>Stairs',
          snowmobileGarageCorridor: 'Snowmobile Garage Corridor',
          snowmobileGarage: 'Snowmobile<br/>Garage',
          greatRoomStairs: 'Great<br/>Room<br/>Stairs',
          storageRoom: 'Storage<br/>Room',
          wineCellar: 'Wine<br/>Cellar',
          wineStock: 'Wine<br/>Stock',
          basementHallway: 'Basement<br/>Hallway',
          backyardStairs: 'Backyard<br/>Stairs',
          mainStairs: 'Main<br/>Stairs',
          mainGarage: 'Main Garage',
          garageEntrance: 'Garage<br/>Entrance',
          westEntrance: 'West<br/>Entrance',
          gamingRoomHallway: 'Gaming Room<br/>Hallway',
          gamingRoom: 'Gaming<br/>Room',
          bar: 'Bar',
          greatRoom: 'Great Room',
          diningRoom: 'Dining Room',
          mainEntrance: 'Main<br/>Entrance',
          trophyRoom: 'Trophy Room',
          kitchenHallway: 'Kitchen<br/>Hallway',
          kitchen: 'Kitchen',
          libraryHallway: 'Library Hallway',
          libraryEntrance: 'Library<br/>Entrance',
          library: 'Library',
          bedroomTerrace: 'Bedroom<br/>Terrace',
          fireplaceHallway: 'Fireplace<br/>Hallway',
          bedroomHallway: 'Bedroom<br/>Hallway',
          masterBathroom: 'Master<br/>Bathroom',
          masterBedroom: 'Master Bedroom',
          office: 'Office',
          woodenTrail: 'Wooden<br/>Trail',
          campfireWood: 'Campfire Wood',
          backyard: 'Backyard',
          gazeebo: 'Gazeebo',
          cliffsideStairs: 'Cliffside<br/>Stairs',
          cliffsideWoods: 'Cliffside Woods',
          backyardPatio: 'Backyard Patio',
          officeBalcony: 'Office<br/>Balcony',
          helipadTrail: 'Helipad<br/>Trail',
          helipad: 'Helipad',
          frontYardPatio: 'Front Yard<br/>Patio',
          frontYard: 'Front Yard',
          bathroomBalcony: 'Bathroom<br/>Balcony',
          libraryBalcony: 'Library<br/>Balcony',
          bedroomBalcony: 'Bedroom<br/>Balcony',
          snowmobiles: 'Snowmobiles'
        },
        club: {
          spawnMainEntrance: 'Үндсэн орц',
          spawnShippingDocks: 'Бараа ачилт',
          spawnWarehouse: 'Агуулах',
          spawnConstructionSite: 'Барилгын талбай',
          easternSubroof: 'Зүүн-хажуу<br/>дээвэр',
          constructionSite: 'Барилгын<br/>талбай',
          container: 'Чингэлэг',
          graffitiArea: 'Графитын хэсэг',
          recreationArea: 'Тоглоомын<br/>талбай',
          junkyard: 'Хогийн цэг',
          VIPParking: 'VIP зогсоол',
          mainGate: 'Үндсэн хаалга',
          parking: 'Зогсоол',
          kennels: 'Нохойн үүр',
          trash: 'Хог',
          centralSubroof: 'Төв-хажуу<br/>дээвэр',
          easternRoof: 'Зүүн дээвэр',
          centralRoof: 'Төв<br/>дээвэр',
          westernRoof: 'Баруун дээвэр',
          balcony: 'Тагт',
          escapeTunnel: 'Оргох<br/>хонгил',
          arsenalRoom: 'Зэвсгийн<br/>өрөө',
          basementHallway: 'Суурийн гудам',
          memorialRoom: 'Дурсгалын өрөө',
          utilityRoom: 'Үйлчилгээний<br/>өрөө',
          oilPit: 'Тосон цооног',
          centralStairs: 'Төв<br/>шат',
          church: 'Сүм',
          frontPorch: 'Урд довжоо',
          garage: 'Гараж',
          lobby: 'Үүдний<br/>өрөө',
          stockRoom: 'Барааны өрөө',
          garageStorage: 'Гаражийн<br/>агуулах',
          lounge: 'Амралтын өрөө',
          bar: 'Баар',
          centralHallway: 'Төв гудам',
          kitchen: 'Гал зуух',
          kitchenEntrance: 'Гал зуухны<br/>орц',
          westernHallway: 'Баруун<br/>гудам',
          stripClub: 'Тайчих клуб',
          junkyardEntrance: 'Хогийн<br/>цэгийн<br/>орц<br/>',
          sideEntrance: 'Хажуу орц',
          changingRoom: 'Хувцас солих<br/>өрөө',
          bedroom: 'Унтлагын<br/>өрөө',
          bathroom: 'Бие засах<br/>өрөө',
          bedroomHallway: 'Унтлагын өрөөний гудам',
          logisticOffice: 'Логистикын<br/>оффис',
          gym: 'Дасгалын<br/>өрөө',
          secretStash: 'Нууц<br/>өрөө',
          CCTVRoom: 'CCTV-н өрөө',
          cashRoom: 'Мөнгөний<br/>өрөө',
          easternStairs: 'Зүүн<br/>шат'
        },
        consulate: {
          spawnRiotBarricade: 'Riot Barricade',
          spawnPoliceLine: 'Police Line',
          spawnGasStation: 'Gas Station',
          spawnSideEntrance: 'Side Entrance',
          exitStairs: 'Exit<br/>Stairs',
          garage: 'Garage',
          basementCorridor: 'Basement Corridor',
          securityRoom: 'Security Room',
          cafeteria: 'Cafeteria',
          mainStairs: 'Main Stairs',
          lockerHallway: 'Locker<br/>Hallway',
          serviceStairs: 'Service<br/>Stairs',
          electricRoom: 'Electric<br/>Room',
          storageRoom: 'Storage<br/>Room',
          archives: 'Archives',
          archivesCorridor: 'Archives<br/>Corridor',
          pressRoom: 'Press Room',
          westCorridor: 'West Corridor',
          publicBathroom: 'Public<br/>Bathroom',
          antechamber: 'Antechamber',
          lobby: 'Lobby',
          eastCorridor: 'East<br/>Corridor',
          tellers: 'Tellers',
          visaOffice: 'Visa Office',
          visaEntrance: 'Visa<br/>Entrance',
          frontDoor: 'Front<br/>Door',
          balcony: 'Balcony',
          copyRoom: 'Copy Room',
          cabinet: 'Cabinet',
          administrationOffice: 'Administration<br/>Office',
          breakRoom: 'Break<br/>Room',
          frontOffice: 'Front Office',
          meetingRoom: 'Meeting<br/>Room',
          hallway: 'Hallway',
          consulFrontDesk: 'Consul<br/>Front<br/>Desk',
          privateBathroom: 'Private<br/>Bathroom',
          waitingRoom: 'Waiting<br/>Room',
          consulateOffice: 'Consulate<br/>Office',
          garageWay: 'Garage Way',
          courtyard: 'Courtyard',
          backCourtyard: 'Back Courtyard',
          sideEntrance: 'Side Entrance',
          dumpster: 'Dumpster',
          parking: 'Parking',
          gardens: 'Gardens',
          fountain: 'Fountain',
          emergencyExit: 'Emergency<br/>Exit',
          garageRoof: 'Garage<br/>Roof',
          memorialGarden: 'Memorial Garden',
          policeLine: 'Police Line',
          riotBarracade: 'Riot Barracade',
          eastFrontYard: 'East Front Yard',
          westFrontYard: 'West Front Yard',
          frontAlley: 'Front Alley',
          buildingRoof: 'Building Roof'
        },
        coastline: {
          aquarium: 'Aquarium',
          backAlley: 'Back<br/>Alley',
          balcony: 'Balcony (not shown)',
          bathroom: 'Bathroom',
          billiardsRoom: 'Billiards Room',
          blueBar: 'Blue Bar',
          cantina: 'Cantina',
          courtyard: 'Courtyard',
          djBooth: 'DJ Booth (not shown)',
          garageRoof: 'Garage Roof',
          hallOfFame: 'Hall of Fame',
          hallway: 'Hallway',
          hookahDeck: 'Hookah<br/>Deck<br/>(not shown)',
          hookahLounge: 'Hookah Lounge',
          kitchen: 'Kitchen',
          mainEntrance: 'Main<br/>Entrance',
          mainLobby: 'Main<br/>Lobby',
          northStairs: 'North<br/>Stairs',
          office: 'Office',
          penthouse: 'Penthouse',
          pool: 'Pool',
          poolEntrance: 'Pool Entrance',
          poolSide: 'Pool Side',
          rooftop: 'Rooftop',
          ruins: 'Ruins',
          securityRoom: 'Security<br/>Room',
          serviceEntrance: 'Service<br/>Entrance',
          southHallway: 'South Hallway',
          southPromenade: 'South Promenade',
          southStairs: 'South<br/>Stairs',
          sunriseBar: 'Sunrise Bar',
          sunRoom: 'Sun Room',
          theater: 'Theater',
          terrace: 'Terrace',
          toilets: 'Toilets',
          vipLounge: 'VIP Lounge',
          walkway: 'Walkway'
        },
        favela: {
          packagingRoom: 'Packaging<br/>Room',
          footballApartment: 'Football<br/>Apartment',
          armoryRoom: 'Armory<br/>Room',
          auntsApartment: 'Aunt\'s<br/>Apartment',
          auntsBedroom: 'Aunt\'s<br/>Bedroom',
          growRoom: 'Grow<br/>Room',
          bikersApartment: 'Biker\'s<br/>Apartment',
          methLab: 'Meth Lab',
          footballBedroom: 'Football<br/>Bedroom',
          footballOffice: 'Football<br/>Office',
          bikersBedroom: 'Biker\'s<br/>Bedroom',
          backStairs: 'Back<br/>Stairs',
          auntsHall: 'Aunt\'s Hall',
          kidsRoom: 'Kids Room',
          mainStairs: 'Main<br/>Stairs',
          stairHall: 'Stair<br/>Hall',
          roof: 'Roof',
          laundryRoom: 'Laundry<br/>Room',
          vaultRoom: 'Vault<br/>Room',
          bikersGarage: 'Biker\'s<br/>Garage',
          backAlley: 'Back Alley',
          schoolAlley: 'School Alley',
          footballPitch: 'Football Pitch',
          market: 'Market',
          marketAlley: 'Market<br/>Alley',
          schoolRooftops: 'School<br/>Rooftops',
          street: 'Street',
          rooftops: 'Rooftops',
          courtyard: 'Courtyard',
          accessAlley: 'Access Alley',
          shop: 'Shop<br/>(not shown)',
          marketRooftops: 'Market Rooftops'
        },
        hereford: {
          spawnTrainingCourse: 'Training Course',
          spawnParking: 'Parking',
          spawnShootingRange: 'Shooting Range',
          armory: 'Armory',
          lockers: 'Lockers',
          corridor: 'Corridor',
          mainStairs: 'Main<br/>Stairs',
          maintenanceArea: 'Maintenance<br/>Area',
          briefingRoom: 'Briefing<br/>Room',
          basementEntrance: 'Basement<br/>Entrance',
          garage: 'Garage',
          TVRoom: 'TV Room',
          garageCorridor: 'Garage Corridor',
          kitchen: 'Kitchen',
          corridor1: 'Corridor<br/>1',
          diningRoom: 'Dining<br/>Room',
          pianoLounge: 'Piano Lounge',
          office: 'Office',
          masterBedroom: 'Master Bedroom',
          backAccess: 'Back<br/>Access',
          laundryRoom: 'Laundry<br/>Room',
          bathroom: 'Bathroom',
          kidsBedroom: 'Kids<br/>Bedroom',
          ballisticMatDepot: 'Ballistic Mat<br/>Depot',
          storage: 'Storage',
          storageCorridor: 'Storage<br/>Corridor',
          dummyDepot: 'Dummy Depot',
          workshop: 'Workshop',
          shootingRangeEastEntrance: 'Shooting Range<br/>East Entrance',
          shootingRangeWestEntrance: 'Shooting Range<br/>West Entrance',
          tireSetting: 'Tire Setting',
          observationRamp: 'Observation Ramp',
          barracks: 'Barracks',
          busBackAlley: 'Bus Back<br/>Alley',
          rappelTower: 'Rappel<br/>Tower',
          terrace: 'Terrace',
          frontAccess: 'Front Access',
          chapelGate: 'Chapel Gate',
          forkliftArea: 'Forklift<br/>Area',
          sideStairsAlley: 'Side Stairs<br/>Alley',
          sideStairs: 'Side<br/>Stairs',
          garageTop: 'Garage Top',
          rooftop: 'Rooftop',
          parkingEntrance: 'Parking Entrance'
        },
        house: {
          spawnConstructionSite: 'Барилгын талбай',
          spawnRiverDocks: 'Голын эрэг',
          spawnAPCArea: 'Хуягтын хэсэг',
          spawnSideStreet: 'Хажуу гудамж',
          depot: 'Амбаар',
          trainingRoom: 'Дасгалын өрөө',
          kitchenStairs: 'Гал зуухны<br/>шат',
          sideStairs: 'Хажуу<br/>шат',
          laundryRoom: 'Угаалгын<br/>өрөө',
          garage: 'Гараж',
          livingRoom: 'Том<br/>өрөө',
          backEntrance: 'Хойд орц',
          lobby: 'Үүдний өрөө',
          kitchen: 'Гал зуух',
          office: 'Оффис',
          diningRoom: 'Хоолны<br/>өрөө',
          workshop: 'Ажлын хэсэг',
          kidsBedroom: 'Хүүхдийн<br/>унтлагын өрөө',
          upperHallway: 'Дээд<br/>гудам',
          lobbyStairs: 'Үүдний<br/>шат',
          walkIn: 'Харанхуй<br/>өрөө',
          masterBedroom: 'Унтлагын том өрөө',
          bathroom: 'Бие засах<br/>өрөө',
          sideStreet: 'Хажуу<br/>гудамж',
          garageEntrance: 'Гаражийн<br/>орц',
          garden: 'Цэцэрлэг',
          backAlley: 'Арын гудам',
          patio: 'Арын талбай',
          jacuzzi: 'Жакузи',
          basementStairs: 'Суурийн<br/>шат',
          treehouseAlley: 'Модны<br/>байшинтай<br/>гудам',
          frontYard: 'Урд талбай',
          frontStreet: 'Урд гудамж',
          frontPorch: 'Урд довжоо',
          backPorch: 'Хойд довжоо',
          backPorchTop: 'Хойд саравч',
          frontPorchTop: 'Урд саравч',
          rooftop: 'Дээвэр'
        },
        kanal: {
          spawnFloatingDock: 'Floating Dock',
          spawnSailboats: 'Sailboats',
          spawnConstructionSite: 'Construction Site',
          boatGarage: 'Boat Garage',
          boatSupplies: 'Boat Supplies',
          pipes: 'Pipes',
          boatSuppliesHallway: 'Boat<br/>Supplies<br/>Hallway',
          lockerRoom: 'Locker Room',
          coastGuardStairs: 'Coast Guard<br/>Stairs',
          showers: 'Showers',
          showersCorridor: 'Showers<br/>Corridor',
          loadingDock: 'Loading Dock',
          machineHallway: 'Machine<br/>Hallway',
          controlCenterStairs: 'Control<br/>Center<br/>Stairs',
          holdingRoom: 'Holding<br/>Room',
          holdingRoomHallway: 'Holding<br/>Room<br/>Hallway',
          radio: 'Radio',
          coastGuardOffice: 'Coast Guard<br/>Office',
          archives: 'Archives',
          coastGuardHall: 'Coast<br/>Guard<br/>Hall',
          mainEntrance: 'Main<br/>Entrance',
          lounge: 'Lounge',
          bridge: 'Bridge',
          modelRoom: 'Model Room',
          securityRoom: 'Security<br/>Room',
          projectorRoom: 'Projector<br/>Room',
          mapsOffice: 'Maps<br/>Office',
          mapsOfficeHallway: 'Maps Office<br/>Hallway',
          kitchen: 'Kitchen',
          cafeteria: 'Cafeteria',
          plantsHallway: 'Plants Hallway',
          thirdFloorExit: 'Third<br/>Floor<br/>Exit',
          controlRoom: 'Control<br/>Room',
          electricRoom: 'Electric<br/>Room',
          controlRoomHallway: 'Control Room Hallway',
          serverRoom: 'Server<br/>Room',
          lockgate: 'Lockgate',
          quayContainers: 'Quay Containers',
          lockgateTunnel: 'Lockgate<br/>Tunnel',
          waterWalkway: 'Water Walkway',
          quayConstruction: 'Quay Construction',
          constructionSite: 'Construction<br/>Site',
          constructionEntrance: 'Construction<br/>Entrance',
          parkingAlley: 'Parking Alley',
          parkingEntrance: 'Parking<br/>Entrance',
          middleRoad: 'Middle<br/>Road',
          forkliftAlley: 'Forklift<br/>Alley',
          frontLawn: 'Front Lawn',
          basementStairs: 'Basement Stairs',
          coastGuardRoof: 'Coast<br/>Guard<br/>Roof',
          bridgeRoof: 'Bridge<br/>Roof',
          roofBrickPile: 'Roof<br/>Brick<br/>Pile',
          balcony: 'Balcony',
          controlCenterRoof: 'Control<br/>Center<br/>Roof',
          dockStairs: 'Dock Stairs',
          parking: 'Parking',
          boatCrane: 'Boat Crane',
          mapArchives: 'Map<br/>Archives'
        },
        kafe: {
          spawnRiverDocks: 'River Docks',
          spawnChristmasMarket: 'Christmas Market',
          spawnPark: 'Park',
          laundryRoom: 'Laundry<br/>Room',
          frontStairs: 'Front<br/>Stairs',
          bakery: 'Bakery',
          bakeryKitchen: 'Bakery<br/>Kitchen',
          kitchenPrep: 'Kitchen<br/>Prep',
          kitchenGrill: 'Kitchen Grill',
          kitchenPickUp: 'Kitchen<br/>Pick Up',
          coldRoom: 'Cold Room',
          diningRoom: 'Dining Room',
          backStairs: 'Back<br/>Stairs',
          coldRoomCorridor: 'Cold<br/>Room<br/>Corridor',
          VIPSection: 'VIP<br/>Section',
          barStairs: 'Bar<br/>Stairs',
          storage: 'Storage',
          museumEntrance: 'Museum<br/>Entrance',
          miningRoom: 'Mining Room',
          trainMuseum: 'Train Museum',
          pillarDiningRoom: 'Pillar Dining Room',
          mainCorridor: 'Main<br/>Corridor',
          readingRoomCorridor: 'Reading Room Corridor',
          readingRoom: 'Reading Room',
          fireplaceHall: 'Fireplace<br/>Hall',
          cigarShop: 'Cigar Shop',
          cigarLounge: 'Cigar Lounge',
          bar: 'Bar',
          barBackstore: 'Bar<br/>Backstore',
          washrooms: 'Wash-<br/>rooms',
          washroomCorridor: 'Washroom Corridor',
          cocktailLounge: 'Cocktail<br/>Lounge',
          cocktailLoungeEntrance: 'Cocktail<br/>Lounge<br/>Entrance',
          westMainStreet: 'West Main Street',
          mainStreet: 'Main Street',
          eastMainStreet: 'East Main Street',
          bakeryParking: 'Bakery<br/>Parking',
          bakeryRoof: 'Bakery Roof',
          cafeRoofTop: 'Cafe Roof Top',
          terrace: 'Terrace',
          backAlley: 'Back Alley',
          garrage: 'Garrage',
          parkAlley: 'Park<br/>Alley'
        },
        oregon: {
          spawnJunkyard: 'Хогийн цэг',
          spawnStreet: 'Гудамж',
          spawnConstructionSite: 'Барилгын талбай',
          towerStairs: 'Цамхагийн шат',
          boilerRoom: 'Халаагуурын<br/>өрөө',
          electricRoom: 'Цахилгааны<br/>өрөө',
          bunkerEntrance: 'Бункерийн<br/>орц',
          bunker: 'Бункер',
          basementCorridor: 'Суурийн<br/>Хонгил',
          supplyRoom: 'Хангамжийн<br/>өрөө',
          laundryRoom: 'Угаалгын өрөө',
          laundryStorage: 'Угаалгын<br/>агуулах',
          laundryStairs: 'Угаалгын<br/>шат',
          office: 'Оффис',
          diningHall: 'Зоогийн<br/>өрөө',
          diningHallCorridor: 'Зоогийн<br/>өрөөний хонгил',
          showers: 'Шүршүүр',
          kitchen: 'Галын өрөө',
          bathroom: 'Бие засах өрөө',
          dormStairs: 'Дотуур байр',
          pantry: 'Зоорь',
          bathroomCorridor: 'Бие засах<br/>өрөөний хонгил',
          classroom: 'Анги',
          lobby: 'Үүдний өрөө',
          mainStairs: 'Үндсэн шат',
          meetingHall: 'Уулзалтын танхим',
          rearStage: 'Хойд шат',
          garage: 'Гараж',
          officeStorage: 'Оффисын<br/>агуулах',
          kidsDorm: 'Хүүхдийн<br/>дотуур байр',
          dormMainHall: 'Дотуур байрны<br/>үндсэн танхим',
          smallDorms: 'Жижиг дотуур байр',
          armoryCorridor: 'Зэвсгийн агуулахын<br/>хонгил',
          masterBedroom: 'Унтлагын<br/>том өрөө',
          armory: 'Зэвсгийн агуулах',
          walkIn: 'Харанхуй өрөө',
          attic: 'Дээврийн хөндий',
          watchTower: 'Харуулын цамхаг',
          busYard: 'Автобусны талбай',
          junkyard: 'Хогийн цэг',
          farmlands: 'Ногооны талбай',
          shootingRange: 'Буудлагын<br/>талбай',
          constructionSite: 'Барилгын талбай',
          parking: 'Зогсоол',
          mainEntrance: 'Үндсэн орц',
          street: 'Гудамж',
          balcony: 'Тагт',
          diningHallRoof: 'Зоогийн өрөөний<br/>дээвэр',
          officeRoof: 'Оффисын дээвэр',
          meetingHallEntrance: 'Уулзалтын<br/>танхимын орц',
          garageRoof: 'Гаражийн дээвэр',
          dormsRoof: 'Дотуур байрны<br/>дээвэр',
          meetingHallRoof: 'Уулзалтын<br/>танхимын<br/>дээвэр',
          supplyCloset: 'Хангамжийн<br/>шүүгээ'
        },
        plane: {
          spawnOfficialEntrance: 'Official Entrance',
          spawnReporterEntrance: 'Reporter Entrance',
          spawnServiceEntrance: 'Service Entrance',
          pressBathroom: 'Pr.BR',
          meetingRoom: 'Meeting Room',
          frontHallway: 'Front<br/>Hallway',
          executiveOffice: 'Executive<br/>Office',
          mainEntrance: 'Main Entrance',
          frontStairs: 'Front Stairs',
          pantry: 'Pantry',
          kitchen: 'Kitchen',
          executiveHallway: 'Executive Hallway',
          executiveBedroom: 'Executive<br/>Bedroom',
          changeRoom: 'Change<br/>Room',
          laund: 'Laund.',
          frontServiceEntrance: 'Front Service<br/>Entrance',
          rightWing: 'Right Wing',
          backServiceEntrance: 'Back Service<br/>Entrance',
          reporterEntrance: 'Reporter Entrance',
          leftWing: 'Left Wing',
          staffSection: 'Staff Section',
          securityRoom: 'Security<br/>Room',
          pressSectionA: 'Press<br/>Section A',
          pressSectionB: 'Press<br/>Section B',
          backStairs: 'Back Stairs',
          cargoHold: 'Cargo Hold',
          serviceCorridor: 'Service Corridor',
          storage: 'Storage',
          luggageHold: 'Luggage<br/>Hold',
          firstAidStation: 'First Aid Station',
          cargoFrontEntrance: 'Cargo Front<br/>Entrance',
          cockpitStairs: 'Cockpit Stairs',
          cabinStaff: 'Cabin<br/>Staff',
          radioCabin: 'Radio Cabin',
          cabin: 'Cabin',
          caterer: 'Caterer',
          serverRoomA: 'Server Room A',
          serverRoomB: 'Server Room B',
          technicalSeating: 'Technical Seating',
          ladderRoom: 'Ladder<br/>Room'
        },
        skyscraper: {
          helipad: 'Helipad',
          tower: 'Tower',
          ventilationUnits: 'Ventilation Units',
          kitchen: 'Kitchen',
          pantry: 'Pantry',
          deliveryRoom: 'Delivery<br/>Room',
          houseLobby: 'House Lobby',
          houseEntrance: 'House<br/>Entrance',
          mainEntrance: 'Main<br/>Entrance',
          reception: 'Reception',
          bedroom: 'Bedroom',
          closet: 'Closet',
          bathroom: 'Bathroom',
          houseStairs: 'House<br/>Stairs',
          restaurant: 'Restaurant',
          toilet: 'Toilet',
          bbq: 'BBQ',
          backHallway: 'Back Hallway',
          mainStairs: 'Main<br/>Stairs',
          geishaRoom: 'Geisha<br/>Room',
          hallway: 'Hallway',
          karaoke: 'Karaoke',
          teaRoom: 'Tea Room',
          taiko: 'Taiko',
          terrace: 'Terrace',
          backStairs: 'Back<br/>Stairs',
          houseBalcony: 'House<br/>Balcony',
          exhibition: 'Exhibition',
          lounge: 'Lounge',
          workOffice: 'Work<br/>Office',
          clearance: 'Clearance',
          peacefullTree: 'Peacefull<br/>Tree',
          contemplationGarden: 'Contemplation<br/>Garden',
          westGarden: 'West<br/>Garden',
          bridge: 'Bridge',
          gazeebo: 'Gazeebo',
          restBalcony: 'Rest.<br/>Balcony',
          northGarden: 'North<br/>Garden',
          eastGarden: 'East<br/>Garden',
          sandGarden: 'Sand<br/>Garden',
          sidePath: 'Side<br/>Path',
          sideStairs: 'Side<br/>Stairs',
          dragonStatue: 'Dragon<br/>Statue',
          coveredWalkway: 'Covered<br/>Walkway'
        },
        yacht: {
          spawnSubmarine: 'Submarine',
          spawnZodiak: 'Zodiak',
          spawnSnowMobile: 'Snow Mobile',
          mapsRoom: 'Maps Room',
          cockpit: 'Cockpit',
          cockpitHallway: 'Cockpit Hallway',
          captainsOffice: 'Captain\'s<br/>Office',
          cockpitBalcony: 'Cockpit<br/>Balcony',
          topDeckStairs: 'Top<br/>Deck<br/>Stairs',
          helipadEntrance: 'Helipad<br/>Entrance',
          helipad: 'Helipad',
          spaDeck: 'Spa<br/>Deck',
          eastDeck: 'East Deck',
          westDeck: 'West Deck',
          frontDeck: 'Front<br/>Deck',
          masterBedroom: 'Master<br/>Bedroom',
          casino: 'Casino',
          pokerRoom: 'Poker<br/>Room',
          bathroom: 'Bath-<br/>room',
          bedroomHallway: 'Bedroom Hallway',
          casinoHallway: 'Casino Hallway',
          globeHallway: 'Globe<br/>Hallway',
          lounge: 'Lounge',
          cafeteria: 'Cafeteria',
          engine: 'Engine',
          backEntrance: 'Back<br/>Entrance',
          rearDeck: 'Rear<br/>Deck',
          serverRoom: 'Server<br/>Room',
          engineStorage: 'Engine<br/>Storage',
          engineControl: 'Engine<br/>Control',
          backStairs: 'Back<br/>Stairs',
          emergencyExit: 'Emergency Exit',
          engineHallway: 'Engine Hallway',
          frontStairs: 'Front<br/>Stairs',
          kitchen: 'Kitchen',
          staffDormitory: 'Staff<br/>Dormitory',
          westBalcony: 'West Balcony',
          eastBalcony: 'East Balcony',
          kitchenHallway: 'Kitchen Hallway',
          kitchenStairs: 'Kitchen Stairs',
          kitchenPantry: 'Kitchen<br/>Pantry',
          infirmary: 'Infirmary',
          borealSubRoom: 'Boreal Sub<br/>Room',
          cafeteriaHallway: 'Cafeteria Hallway',
          engineUtility: 'Engine<br/>Utility',
          submarine: 'Submarine',
          westGlacier: 'West Glacier',
          eastHullBreach: 'East Hull<br/>Breach',
          eastGlacier: 'East Glacier',
          frozenRiver: 'Frozen River',
          zodiac: 'Zodiac',
          westHullBreach: 'West Hull Breach',
          kingOfTheWorld: 'King of<br/>the World',
          roof: 'Roof',
          anchorName: 'Anchor',
          aklarkSubEntrance: 'Aklark Sub<br/>Entrance'
        }
      }
    };

  R6MapsLangTerms.registerLanguage(name, terms);

  return  {
    name: name,
    terms: terms
  };
})(R6MapsLangTerms);
