'use strict';

var R6MapsLangTermsMongolian = (function(R6MapsLangTerms, undefined) {
  var name = 'mn',
    terms = {
      general: {
        pageTitleSelectMap: 'R6Maps.com - Газар сонго',
        pageTitleStart: 'R6Maps.com',
        cameraViewCaption: '{floorName} камерын дүрс',
        shortcutTip: 'Shortcut: {shortcut}',
        menu: 'Цэс',
        about: 'Танилцуулга',
        languageHeader: 'Хэл',
        optionsHeader: 'Тохируулга',
        labelLosOpacity: 'Camera line-of-sight opacity',
        labelLosDefault: '(Анхны утга)',
        labelLos105: '(Айн?)',
        labelLos110: '(Дэндүү!)',
        labelRoomLabelStyle: 'Өрөөний нэрийн загвар',
        labelNumberFloorsToDisplay: 'Харуулах давхарын тоо',
        lockPanning: 'Гүйлтийг цоожлох',
        lockZooming: 'Томролтыг цоожлох',
        fullScreen: 'Дэлгэц дүүрэн',
        enableScreenshots: 'Зураг авах боломж',
        contributions: 'Хандив',
        supportSiteNote: 'Бага зэргийн хандив өргөн намайг дэмжихийг хүсье. :)',
        donateImg: 'https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif',
        latestUpdate: '2017 оны 2 сарын шинэчлэл',
      },
      sessions: {
        button: 'Sessions (BETA)'
      },
      roomLabelStyles: {
        Dark: 'Бараан',
        Light: 'Цайвар (анхны утга)',
        DarkAndLarge: 'Том, бараан',
        LightAndLarge: 'Том, цайвар',
        DarkAndSmall: 'Жижиг, бараан',
        LightAndSmall: 'Жижиг, цайвар',
        DisplayNone: 'Унтраах'
      },
      floorDisplayOptions: {
        one: '1 - Дан',
        two: '2 - Зэрэгцээ',
        four: '4 - Дөрвөлжин'
      },
      selectMaps: {
        selectAMap: 'Газар сонго',
        homeLink: 'Газар сонго'
      },
      compass: {
        letterN: 'Х',
        letterE: 'З',
        letterS: 'Ө',
        letterW: 'Б'
      },
      floorNames: {
        basement: { full: 'Суурь', short: 'С' },
        firstFloor: { full: '1-р давхар', short: '1' },
        secondFloor: { full: '2-р давхар', short: '2' },
        thirdFloor: { full: '3-р давхар', short: '3' },
        fourthFloor: { full: '4-р давхар', short: '4' },
        roof: { full: 'Дээвэр', short: 'Д' }
      },
      objectives: {
        bombShortA: 'A',
        bombShortB: 'B',
        bomb: 'Бөмбөг',
        hostageShort: 'H',
        hostage: 'Барьцаа',
        secureShort: 'S',
        secure: 'Эзлэх',
        showAll: 'Бүгдийг харуул'
      },
      legend: {
        breakableWalls: 'Эвдэрдэг хана',
        breakableFloorTraps: 'Эвдэрдэг шалны хаалга',
        ceilingHatches: 'Таазны хаалга',
        lineOfSightWalls: 'Нэвт буудаж болох хана',
        lineOfSightFloors: 'Нэвт буудаж болох шал',
        droneTunnels: 'Дроны хонгил',
        objectives: 'Бай',
        insertionPoints: 'Эхлэлийн цэг',
        securityCameras: 'Аюулгүй байдлын камер',
        skylights: 'Таазны цонх',
        onFloorAboveOrBelow: 'Дээд эсвэл доод давхарт',
        cameraLineOfSight: 'Камерын харах өнцөг',
        ladders: 'Авирдаг шат'
      },
      spawnPoints: {
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        e: 'E'
      },
      mapNames: {
        bank: 'Банк',
        bartlett: 'Бартлетт И.С.',
        border: 'Хил',
        chalet: 'Дүнзэн байшин',
        club: 'Клубын байр',
        consulate: 'Консулын газар',
        coastline: 'Далайн эрэг',
        favela: 'Фавела',
        hereford: 'Херфорд',
        house: 'Байшин',
        kanal: 'Суваг',
        kafe: 'Достоевский кафе',
        oregon: 'Орегон',
        plane: 'Онгоц',
        skyscraper: 'Өндөр байшин',
        yacht: 'Дарвуулт хөлөг'
      },
      mapRooms: {
        bank: {
          spawnBoulevard: 'Boulevard',
          spawnBackAlley: 'Back Alley',
          printerRoom: 'Printer Room',
          parkingLot: 'Parking Lot',
          boulevard: 'Boulevard',
          jewelryFront: 'Jewelry Front',
          plaza: 'Plaza',
          mainEntrance: 'Main Entrance',
          garageRamp: 'Garage<br/>Ramp',
          exteriorParking: 'Exterior Parking',
          garageRoof: 'Garage<br/>Roof',
          alleyAccess: 'Alley Access',
          backAlleyRooftop: 'Back Alley<br/>Rooftop',
          backAlley: 'Back Alley',
          highRoof: 'High Roof',
          lowRoof: 'Low Roof',
          vault: 'Vault',
          goldVault: 'Gold<br/>Vault',
          serverRoomStairs: 'Server Room Stairs',
          serverRoom: 'Server Room',
          CCTVRoom: 'CCTV<br/>Room',
          loadingDock: 'Loading Dock',
          secureHallway: 'Secure<br/>Hallway',
          sewer: 'Sewer',
          lockers: 'Lockers',
          vaultLobby: 'Vault Lobby',
          vaultEntrance: 'Vault<br/>Entrance',
          mainStairway: 'Main<br/>Stairway',
          bankGarage: 'Bank Garage',
          elevators: 'Elevators',
          tellersOffice: 'Tellers\'<br/>Office',
          archives: 'Archives',
          tellers: 'Tellers',
          loanOffice: 'Loan Office',
          officeHallway: 'Office Hallway',
          skylightStairwell: 'Skylight<br/>Stairwell',
          lobby: 'Lobby',
          openArea: 'Open Area',
          staffRoom: 'Staff Room',
          electricalRoom: 'Electrical<br/>Room',
          adminOffice: 'Admin Office',
          ATMs: 'ATMs',
          executiveHallway: 'Executive<br/>Hallway',
          frontDesk: 'Front<br/>Desk',
          executiveLounge: 'Executive<br/>Lounge',
          CEOOffice: 'CEO<br/>Office',
          janitorCloset: 'Janitor Closet',
          hallway: 'Hallway',
          terrace: 'Terrace',
          stockTradingRoom: 'Stock<br/>Trading<br/>Room',
          conferenceRoom: 'Conference<br/>Room'
        },
        bartlett: {
          archwayHall: 'Archway Hall',
          archwaylHallway: 'Archway Hallway',
          backAlley: 'Back Alley',
          bathroom: 'Bath-<br/>room',
          campusField: 'Campus<br/>Field',
          classroom: 'Classroom',
          coatRoom: 'Coat<br/>Room',
          compassHallway: 'Compass Hallway',
          courtyard: 'Courtyard',
          centralHallway: 'Central<br/>Hallway',
          diningRoom: 'Dining Room',
          eastBalcony: 'East Balcony<br/>(not shown)',
          eastCorridor: 'East<br/>Corridor',
          eastStairs: 'East<br/>Stairs',
          festival: 'Festival',
          frontEntrance: 'Front Entrance',
          frontOffice: 'Front<br/>Office',
          frontPatio: 'Front Patio',
          gardenPass: 'Garden<br/>Pass',
          kitchen: 'Kitchen',
          lobby: 'Lobby',
          lounge: 'Lounge',
          lowerLibrary: 'Lower<br/>Library',
          mainGate: 'Main<br/>Gate',
          mainOffice: 'Main Office',
          modelHall: 'Model Hall',
          pantry: 'Pantry',
          parking: 'Parking',
          pianoRoom: 'Piano Room',
          readingRoom: 'Reading Room',
          roof: 'Roof',
          rowingMuseum: 'Rowing<br/>Museum',
          serviceRoom: 'Service<br/>Room',
          terrace: 'Terrace',
          trophyRoom: 'Trophy<br/>Room',
          upperLibrary: 'Upper<br/>Library',
          vistaHallway: 'Vista<br/>Hallway',
          westBalcony: 'West Balcony<br/>(not shown)',
          westCorridor: 'West<br/>Corridor'
        },
        border: {
          armoryLockers: 'Зэвсгийн<br/>шүүгээ',
          tellers: 'Касс',
          ventilationRoom: 'Агаар-<br/>жуулалтын<br/>өрөө',
          exitHallway: 'Гарах<br/>коридор',
          supplyCorridor: 'Хангамжийн<br/>коридор',
          detention: 'Хорио',
          customsInspection: 'Гаалийн шалган',
          customsDesk: 'Гаалийн<br/>оффис',
          centralStairs: 'Төв шат',
          serverRoom: 'Серверийн өрөө',
          supplyRoom: 'Хангамжийн<br/>өрөө',
          workshop: 'Ажлын<br/>хэсэг',
          mainLobby: 'Гол<br/>үүд',
          bathroom: 'Бие засах<br/>өрөө',
          waitingRoom: 'Хүлээлгийн<br/>өрөө',
          eastStairs: 'Зүүн<br/>шат',
          passportCheck: 'Пасспорт<br/>шалган',
          archives: 'Архив',
          offices: 'Оффис',
          officesHallway: 'Оффисын коридор',
          fountain: 'Усан оргилуур',
          mainHallway: 'Гол<br/>коридор',
          armoryDesk: 'Зэвсгийн<br/>агуулахын<br/>оффис',
          securityRoom: 'Аюулгүй<br/>байдлын<br/>өрөө',
          breakRoom: 'Амралтын өрөө',
          spawnEastVehicleEntrance: 'Зүүн орц',
          spawnValley: 'Хөндий',
          spawnWestVehicleExit: 'Баруун гарц',
          westTower: 'Баруун<br/>цамхаг',
          pedestrianExit: 'Явган гарц',
          valley: 'Хөндий',
          parkingLotEntrance: 'Зогсоолын<br/>үүд',
          parkingLot: 'Зогсоол',
          westRoad: 'Баруун зам',
          vehicleCustoms: 'Машины шалган',
          crashScene: 'Ослын талбай',
          eastRoad: 'Зүүн зам',
          pedestrianEntrance: 'Явган хүний<br/>орц',
          pedestrianCustoms: 'Явган хүний<br/>шалган',
          watchTower: 'Харуулын<br/>цамхаг',
          eastAlley: 'Зүүн гудам',
          parkingLotAlley: 'Зогсоолын<br/>гудам',
          northBalcony: 'Хойд тагт',
          eastBalcony: 'Зүүн<br/>тагт',
          westBalcony: 'Баруун<br/>тагт',
          southBalcony: 'Урд тагт',
          roof: 'Дээвэр'
        },
        chalet: {
          spawnFrontYard: 'Урд талбай',
          spawnCampfire: 'Түүдэг',
          spawnCliffside: 'Хадан цохио',
          spawnLakeside: 'Нуурын эрэг',
          libraryStairs: 'Номын сангийн<br/>шат',
          snowmobileGarageCorridor: 'Цаснаа явагчийн гаражийн коридор',
          snowmobileGarage: 'Цаснаа явагчийн<br/>гараж',
          greatRoomStairs: 'Том<br/>өрөөний<br/>шат',
          storageRoom: 'Бараа агуулах',
          wineCellar: 'Дарсны<br/>зоорь',
          wineStock: 'Дарсны<br/>нөөц',
          basementHallway: 'Суурийн<br/>хонгил',
          backyardStairs: 'Арын<br/>шат',
          mainStairs: 'Гол<br/>шат',
          mainGarage: 'Том гараж',
          garageEntrance: 'Гаражийн<br/>орц',
          westEntrance: 'Баруун<br/>орц',
          gamingRoomHallway: 'Тоглоомын<br/>өрөөний<br/>коридор',
          gamingRoom: 'Тоглоомын<br/>өрөө',
          bar: 'Баар',
          greatRoom: 'Том өрөө',
          diningRoom: 'Хоолны өрөө',
          mainEntrance: 'Гол<br/>үүд',
          trophyRoom: 'Шагналын өрөө',
          kitchenHallway: 'Гал зуухны<br/>коридор',
          kitchen: 'Гал зуух',
          libraryHallway: 'Номын сангийн коридор',
          libraryEntrance: 'Номын сангийн<br/>үүд',
          library: 'Номын сан',
          bedroomTerrace: 'Унтлагын өрөөний<br/>дэвсэг',
          fireplaceHallway: 'Задгай зуухны<br/>коридор',
          bedroomHallway: 'Унтлагын<br/>өрөөний<br/>коридор',
          masterBathroom: 'Том<br/>бие засах<br/>өрөө',
          masterBedroom: 'Унтлагын<br/>том өрөө',
          office: 'Оффис',
          woodenTrail: 'Модтой<br/>жим',
          campfireWood: 'Түүдгийн мод',
          backyard: 'Арын талбай',
          gazeebo: 'Бэсээтэг',
          cliffsideStairs: 'Хадан цохионы<br/>шат',
          cliffsideWoods: 'Хадан цохионы мод',
          backyardPatio: 'Арын талбай патио',
          officeBalcony: 'Оффисын<br/>тагт',
          helipadTrail: 'Нисдэг тэрэгний<br/>талбайн зам',
          helipad: 'Нисдэг<br/>тэрэгний<br/>талбай',
          frontYardPatio: 'Урд талбайн<br/>патио',
          frontYard: 'Урд талбай',
          bathroomBalcony: 'Бие засах<br/>өрөөний тагт',
          libraryBalcony: 'Номын сангийн<br/>тагт',
          bedroomBalcony: 'Унтлагын<br/>өрөөний<br/>тагт',
          snowmobiles: 'Цаснаа явагчид'
        },
        club: {
          spawnMainEntrance: 'Үндсэн орц',
          spawnShippingDocks: 'Бараа ачилт',
          spawnWarehouse: 'Агуулах',
          spawnConstructionSite: 'Барилгын талбай',
          easternSubroof: 'Зүүн-хажуу<br/>дээвэр',
          constructionSite: 'Барилгын<br/>талбай',
          container: 'Чингэлэг',
          graffitiArea: 'Графитын хэсэг',
          recreationArea: 'Тоглоомын<br/>талбай',
          junkyard: 'Хогийн цэг',
          VIPParking: 'VIP зогсоол',
          mainGate: 'Үндсэн хаалга',
          parking: 'Зогсоол',
          kennels: 'Нохойн үүр',
          trash: 'Хог',
          centralSubroof: 'Төв-хажуу<br/>дээвэр',
          easternRoof: 'Зүүн дээвэр',
          centralRoof: 'Төв<br/>дээвэр',
          westernRoof: 'Баруун дээвэр',
          balcony: 'Тагт',
          escapeTunnel: 'Оргох<br/>хонгил',
          arsenalRoom: 'Зэвсгийн<br/>өрөө',
          basementHallway: 'Суурийн гудам',
          memorialRoom: 'Дурсгалын өрөө',
          utilityRoom: 'Үйлчилгээний<br/>өрөө',
          oilPit: 'Тосон цооног',
          centralStairs: 'Төв<br/>шат',
          church: 'Сүм',
          frontPorch: 'Урд довжоо',
          garage: 'Гараж',
          lobby: 'Үүдний<br/>өрөө',
          stockRoom: 'Барааны өрөө',
          garageStorage: 'Гаражийн<br/>агуулах',
          lounge: 'Амралтын өрөө',
          bar: 'Баар',
          centralHallway: 'Төв гудам',
          kitchen: 'Гал зуух',
          kitchenEntrance: 'Гал зуухны<br/>орц',
          westernHallway: 'Баруун<br/>гудам',
          stripClub: 'Тайчих клуб',
          junkyardEntrance: 'Хогийн<br/>цэгийн<br/>орц<br/>',
          sideEntrance: 'Хажуу орц',
          changingRoom: 'Хувцас солих<br/>өрөө',
          bedroom: 'Унтлагын<br/>өрөө',
          bathroom: 'Бие засах<br/>өрөө',
          bedroomHallway: 'Унтлагын өрөөний гудам',
          logisticOffice: 'Логистикын<br/>оффис',
          gym: 'Дасгалын<br/>өрөө',
          secretStash: 'Нууц<br/>өрөө',
          CCTVRoom: 'CCTV-н өрөө',
          cashRoom: 'Мөнгөний<br/>өрөө',
          easternStairs: 'Зүүн<br/>шат'
        },
        consulate: {
          spawnRiotBarricade: 'Riot Barricade',
          spawnPoliceLine: 'Police Line',
          spawnGasStation: 'Gas Station',
          spawnSideEntrance: 'Side Entrance',
          exitStairs: 'Exit<br/>Stairs',
          garage: 'Garage',
          basementCorridor: 'Basement Corridor',
          securityRoom: 'Security Room',
          cafeteria: 'Cafeteria',
          mainStairs: 'Main Stairs',
          lockerHallway: 'Locker<br/>Hallway',
          serviceStairs: 'Service<br/>Stairs',
          electricRoom: 'Electric<br/>Room',
          storageRoom: 'Storage<br/>Room',
          archives: 'Archives',
          archivesCorridor: 'Archives<br/>Corridor',
          pressRoom: 'Press Room',
          westCorridor: 'West Corridor',
          publicBathroom: 'Public<br/>Bathroom',
          antechamber: 'Antechamber',
          lobby: 'Lobby',
          eastCorridor: 'East<br/>Corridor',
          tellers: 'Tellers',
          visaOffice: 'Visa Office',
          visaEntrance: 'Visa<br/>Entrance',
          frontDoor: 'Front<br/>Door',
          balcony: 'Balcony',
          copyRoom: 'Copy Room',
          cabinet: 'Cabinet',
          administrationOffice: 'Administration<br/>Office',
          breakRoom: 'Break<br/>Room',
          frontOffice: 'Front Office',
          meetingRoom: 'Meeting<br/>Room',
          hallway: 'Hallway',
          consulFrontDesk: 'Consul<br/>Front<br/>Desk',
          privateBathroom: 'Private<br/>Bathroom',
          waitingRoom: 'Waiting<br/>Room',
          consulateOffice: 'Consulate<br/>Office',
          garageWay: 'Garage Way',
          courtyard: 'Courtyard',
          backCourtyard: 'Back Courtyard',
          sideEntrance: 'Side Entrance',
          dumpster: 'Dumpster',
          parking: 'Parking',
          gardens: 'Gardens',
          fountain: 'Fountain',
          emergencyExit: 'Emergency<br/>Exit',
          garageRoof: 'Garage<br/>Roof',
          memorialGarden: 'Memorial Garden',
          policeLine: 'Police Line',
          riotBarracade: 'Riot Barracade',
          eastFrontYard: 'East Front Yard',
          westFrontYard: 'West Front Yard',
          frontAlley: 'Front Alley',
          buildingRoof: 'Building Roof'
        },
        coastline: {
          aquarium: 'Aquarium',
          backAlley: 'Back<br/>Alley',
          balcony: 'Balcony (not shown)',
          bathroom: 'Bathroom',
          billiardsRoom: 'Billiards Room',
          blueBar: 'Blue Bar',
          cantina: 'Cantina',
          courtyard: 'Courtyard',
          djBooth: 'DJ Booth (not shown)',
          garageRoof: 'Garage Roof',
          hallOfFame: 'Hall of Fame',
          hallway: 'Hallway',
          hookahDeck: 'Hookah<br/>Deck<br/>(not shown)',
          hookahLounge: 'Hookah Lounge',
          kitchen: 'Kitchen',
          mainEntrance: 'Main<br/>Entrance',
          mainLobby: 'Main<br/>Lobby',
          northStairs: 'North<br/>Stairs',
          office: 'Office',
          penthouse: 'Penthouse',
          pool: 'Pool',
          poolEntrance: 'Pool Entrance',
          poolSide: 'Pool Side',
          rooftop: 'Rooftop',
          ruins: 'Ruins',
          securityRoom: 'Security<br/>Room',
          serviceEntrance: 'Service<br/>Entrance',
          southHallway: 'South Hallway',
          southPromenade: 'South Promenade',
          southStairs: 'South<br/>Stairs',
          sunriseBar: 'Sunrise Bar',
          sunRoom: 'Sun Room',
          theater: 'Theater',
          terrace: 'Terrace',
          toilets: 'Toilets',
          vipLounge: 'VIP Lounge',
          walkway: 'Walkway'
        },
        favela: {
          packagingRoom: 'Савлагааны<br/>өрөө',
          footballApartment: 'Хөлбөмбөгийн<br/>байр',
          armoryRoom: 'Зэвсгийн<br/>өрөө',
          auntsApartment: 'Нагацын<br/>байр',
          auntsBedroom: 'Нагацын<br/>унтлагын өрөө',
          growRoom: 'Цэцгийн<br/>өрөө',
          bikersApartment: 'Байкерын<br/>байр',
          methLab: 'Мет лаб',
          footballBedroom: 'Хөлбөмбөгийн<br/>унтлагын өрөө',
          footballOffice: 'Хөлбөмбөгийн<br/>оффис',
          bikersBedroom: 'Байкерын<br/>унтлагын<br/>өрөө',
          backStairs: 'Арын<br/>шат',
          auntsHall: 'Нагацын коридор',
          kidsRoom: 'Хүүхдийн өрөө',
          mainStairs: 'Гол<br/>шат',
          stairHall: 'Шатны<br/>коридор',
          roof: 'Дээвэр',
          laundryRoom: 'Угаалгын<br/>өрөө',
          vaultRoom: 'Шүүгээ',
          bikersGarage: 'Байкерын<br/>гараж',
          backAlley: 'Арын гудам',
          schoolAlley: 'Сургуулийн гудам',
          footballPitch: 'Хөлбөмбөгийн талбай',
          market: 'Зах',
          marketAlley: 'Захын<br/>гудам',
          schoolRooftops: 'Сургуулийн<br/>дээвэр',
          street: 'Гудамж',
          rooftops: 'Дээвэр',
          courtyard: 'Урд талбай',
          accessAlley: 'Хажуу гудам',
          shop: 'Дэлгүүр<br/>(харагдахгүй)',
          marketRooftops: 'Захын дээвэр'
        },
        hereford: {
          spawnTrainingCourse: 'Дасгалын талбай',
          spawnParking: 'Зогсоол',
          spawnShootingRange: 'Буудлагын талбай',
          armory: 'Зэвсгийн агуулах',
          lockers: 'Шүүгээнүүд',
          corridor: 'Хонгил',
          mainStairs: 'Үндсэн<br/>шат',
          maintenanceArea: 'Засварын<br/>хэсэг',
          briefingRoom: 'Мэдээллийн<br/>өрөө',
          basementEntrance: 'Суурийн<br/>орц',
          garage: 'Гараж',
          TVRoom: 'ТВ өрөө',
          garageCorridor: 'Гаражийн хонгил',
          kitchen: 'Гал зуух',
          corridor1: 'Хонгил<br/>1',
          diningRoom: 'Хоолны<br/>өрөө',
          pianoLounge: 'Төгөлдөр хууртай<br/>өрөө',
          office: 'Оффис',
          masterBedroom: 'Унтлагын<br/>том<br/>өрөө',
          backAccess: 'Арын<br/>хаалга',
          laundryRoom: 'Угаалгын<br/>өрөө',
          bathroom: 'Бие засах<br/>өрөө',
          kidsBedroom: 'Хүүхдийн<br/>унтлагын<br/>өрөө',
          ballisticMatDepot: 'Тусгай шалавчны<br/>агуулах',
          storage: 'Агуулах',
          storageCorridor: 'Агуулахын<br/>хонгил',
          dummyDepot: 'Хүүхэлдэйн<br/>агуулах',
          workshop: 'Ажлын хэсэг',
          shootingRangeEastEntrance: 'Буудлагын талбай<br/>Зүүн орц',
          shootingRangeWestEntrance: 'Буудлагын талбай<br/>Баруун орц',
          tireSetting: 'Хураасан дугуй',
          observationRamp: 'Ажиглалтын тавцан',
          barracks: 'Хуаран',
          busBackAlley: 'Автобустай арын<br/>гудам',
          rappelTower: 'Авирдаг<br/>цамхаг',
          terrace: 'Дэвсэг',
          frontAccess: 'Гол орц',
          chapelGate: 'Сүмийн хаалга',
          forkliftArea: 'Ачигчтай<br/>хэсэг',
          sideStairsAlley: 'Хажуу шатны<br/>гудам',
          sideStairs: 'Хажуу<br/>шат',
          garageTop: 'Гаражийн дээвэр',
          rooftop: 'Дээвэр',
          parkingEntrance: 'Зогсоолын орц'
        },
        house: {
          spawnConstructionSite: 'Барилгын талбай',
          spawnRiverDocks: 'Голын эрэг',
          spawnAPCArea: 'Хуягтын хэсэг',
          spawnSideStreet: 'Хажуу гудамж',
          depot: 'Амбаар',
          trainingRoom: 'Дасгалын өрөө',
          kitchenStairs: 'Гал зуухны<br/>шат',
          sideStairs: 'Хажуу<br/>шат',
          laundryRoom: 'Угаалгын<br/>өрөө',
          garage: 'Гараж',
          livingRoom: 'Том<br/>өрөө',
          backEntrance: 'Хойд орц',
          lobby: 'Үүдний өрөө',
          kitchen: 'Гал зуух',
          office: 'Оффис',
          diningRoom: 'Хоолны<br/>өрөө',
          workshop: 'Ажлын хэсэг',
          kidsBedroom: 'Хүүхдийн<br/>унтлагын өрөө',
          upperHallway: 'Дээд<br/>гудам',
          lobbyStairs: 'Үүдний<br/>шат',
          walkIn: 'Харанхуй<br/>өрөө',
          masterBedroom: 'Унтлагын том өрөө',
          bathroom: 'Бие засах<br/>өрөө',
          sideStreet: 'Хажуу<br/>гудамж',
          garageEntrance: 'Гаражийн<br/>орц',
          garden: 'Цэцэрлэг',
          backAlley: 'Арын гудам',
          patio: 'Арын талбай',
          jacuzzi: 'Жакузи',
          basementStairs: 'Суурийн<br/>шат',
          treehouseAlley: 'Модны<br/>байшинтай<br/>гудам',
          frontYard: 'Урд талбай',
          frontStreet: 'Урд гудамж',
          frontPorch: 'Урд довжоо',
          backPorch: 'Хойд довжоо',
          backPorchTop: 'Хойд саравч',
          frontPorchTop: 'Урд саравч',
          rooftop: 'Дээвэр'
        },
        kanal: {
          spawnFloatingDock: 'Хөвдөг зогсоол',
          spawnSailboats: 'Далбаат завьнууд',
          spawnConstructionSite: 'Барилгын талбай',
          boatGarage: 'Завьны гараж',
          boatSupplies: 'Завьны хэрэгсэл',
          pipes: 'Турба',
          boatSuppliesHallway: 'Завьны<br/>хэрэгслийн<br/>гудам',
          lockerRoom: 'Шүүгээтэй<br/>өрөө',
          coastGuardStairs: 'Эргийн харуулын<br/>шат',
          showers: 'Шүршүүр',
          showersCorridor: 'Шүршүүрийн<br/>гудам',
          loadingDock: 'Ачааны зогсоол',
          machineHallway: 'Машины<br/>гудам',
          controlCenterStairs: 'Хяналтын<br/>төвийн<br/>шат',
          holdingRoom: 'Хорих<br/>өрөө',
          holdingRoomHallway: 'Хорих<br/>өрөөний<br/>гудам',
          radio: 'Радио',
          coastGuardOffice: 'Эргийн харуулын<br/>оффис',
          archives: 'Архив',
          coastGuardHall: 'Эргийн<br/>харуулын<br/>коридор',
          mainEntrance: 'Гол<br/>орц',
          lounge: 'Амралтын<br/>өрөө',
          bridge: 'Гүүр',
          modelRoom: 'Загварын өрөө',
          securityRoom: 'Аюулгүй<br/>байдлын<br/>өрөө',
          projectorRoom: 'Проекторын<br/>өрөө',
          mapsOffice: 'Газрын зургийн<br/>өрөө',
          mapsOfficeHallway: 'Газрын зургийн<br/>коридор',
          kitchen: 'Гал зуух',
          cafeteria: 'Цайны газар',
          plantsHallway: 'Ургамалтай гудам',
          thirdFloorExit: '3<br/>давхарын<br/>гарц',
          controlRoom: 'Хяналтын<br/>өрөө',
          electricRoom: 'Цахилгааны<br/>өрөө',
          controlRoomHallway: 'Хяналтын өрөөний коридор',
          serverRoom: 'Серверийн<br/>өрөө',
          lockgate: 'Цоожтой хаалга',
          quayContainers: 'Боомтын чингэлэг',
          lockgateTunnel: 'Цоожтой хаалганы<br/>хонгил',
          waterWalkway: 'Усан гүүр',
          quayConstruction: 'Боомтын<br/>барилгын ажил',
          constructionSite: 'Барилгын<br/>талбай',
          constructionEntrance: 'Барилгын<br/>орц',
          parkingAlley: 'Зогсоолын гудам',
          parkingEntrance: 'Зогсоолын<br/>орц',
          middleRoad: 'Дунд<br/>зам',
          forkliftAlley: 'Ачигчтай<br/>гудам',
          frontLawn: 'Урд зүлэг',
          basementStairs: 'Суурийн шат',
          coastGuardRoof: 'Эргийн<br/>харуулын<br/>дээвэр',
          bridgeRoof: 'Гүүрийн<br/>дээвэр',
          roofBrickPile: 'Дээврийн<br/>овоолсон<br/>тоосго',
          balcony: 'Тагт',
          controlCenterRoof: 'Хяналтын<br/>төвийн<br/>дээвэр',
          dockStairs: 'Усан зогсоолын шат',
          parking: 'Зогсоол',
          boatCrane: 'Завьны кран',
          mapArchives: 'Газрын<br/>зургийн<br/>архив'
        },
        kafe: {
          spawnRiverDocks: 'River Docks',
          spawnChristmasMarket: 'Christmas Market',
          spawnPark: 'Park',
          laundryRoom: 'Laundry<br/>Room',
          frontStairs: 'Front<br/>Stairs',
          bakery: 'Bakery',
          bakeryKitchen: 'Bakery<br/>Kitchen',
          kitchenPrep: 'Kitchen<br/>Prep',
          kitchenGrill: 'Kitchen Grill',
          kitchenPickUp: 'Kitchen<br/>Pick Up',
          coldRoom: 'Cold Room',
          diningRoom: 'Dining Room',
          backStairs: 'Back<br/>Stairs',
          coldRoomCorridor: 'Cold<br/>Room<br/>Corridor',
          VIPSection: 'VIP<br/>Section',
          barStairs: 'Bar<br/>Stairs',
          storage: 'Storage',
          museumEntrance: 'Museum<br/>Entrance',
          miningRoom: 'Mining Room',
          trainMuseum: 'Train Museum',
          pillarDiningRoom: 'Pillar Dining Room',
          mainCorridor: 'Main<br/>Corridor',
          readingRoomCorridor: 'Reading Room Corridor',
          readingRoom: 'Reading Room',
          fireplaceHall: 'Fireplace<br/>Hall',
          cigarShop: 'Cigar Shop',
          cigarLounge: 'Cigar Lounge',
          bar: 'Bar',
          barBackstore: 'Bar<br/>Backstore',
          washrooms: 'Wash-<br/>rooms',
          washroomCorridor: 'Washroom Corridor',
          cocktailLounge: 'Cocktail<br/>Lounge',
          cocktailLoungeEntrance: 'Cocktail<br/>Lounge<br/>Entrance',
          westMainStreet: 'West Main Street',
          mainStreet: 'Main Street',
          eastMainStreet: 'East Main Street',
          bakeryParking: 'Bakery<br/>Parking',
          bakeryRoof: 'Bakery Roof',
          cafeRoofTop: 'Cafe Roof Top',
          terrace: 'Terrace',
          backAlley: 'Back Alley',
          garrage: 'Garrage',
          parkAlley: 'Park<br/>Alley'
        },
        oregon: {
          spawnJunkyard: 'Хогийн цэг',
          spawnStreet: 'Гудамж',
          spawnConstructionSite: 'Барилгын талбай',
          towerStairs: 'Цамхагийн шат',
          boilerRoom: 'Халаагуурын<br/>өрөө',
          electricRoom: 'Цахилгааны<br/>өрөө',
          bunkerEntrance: 'Бункерийн<br/>орц',
          bunker: 'Бункер',
          basementCorridor: 'Суурийн<br/>Хонгил',
          supplyRoom: 'Хангамжийн<br/>өрөө',
          laundryRoom: 'Угаалгын өрөө',
          laundryStorage: 'Угаалгын<br/>агуулах',
          laundryStairs: 'Угаалгын<br/>шат',
          office: 'Оффис',
          diningHall: 'Зоогийн<br/>өрөө',
          diningHallCorridor: 'Зоогийн<br/>өрөөний хонгил',
          showers: 'Шүршүүр',
          kitchen: 'Галын өрөө',
          bathroom: 'Бие засах өрөө',
          dormStairs: 'Дотуур байр',
          pantry: 'Зоорь',
          bathroomCorridor: 'Бие засах<br/>өрөөний хонгил',
          classroom: 'Анги',
          lobby: 'Үүдний өрөө',
          mainStairs: 'Үндсэн шат',
          meetingHall: 'Уулзалтын танхим',
          rearStage: 'Хойд шат',
          garage: 'Гараж',
          officeStorage: 'Оффисын<br/>агуулах',
          kidsDorm: 'Хүүхдийн<br/>дотуур байр',
          dormMainHall: 'Дотуур байрны<br/>үндсэн танхим',
          smallDorms: 'Жижиг дотуур байр',
          armoryCorridor: 'Зэвсгийн агуулахын<br/>хонгил',
          masterBedroom: 'Унтлагын<br/>том өрөө',
          armory: 'Зэвсгийн агуулах',
          walkIn: 'Харанхуй өрөө',
          attic: 'Дээврийн хөндий',
          watchTower: 'Харуулын цамхаг',
          busYard: 'Автобусны талбай',
          junkyard: 'Хогийн цэг',
          farmlands: 'Ногооны талбай',
          shootingRange: 'Буудлагын<br/>талбай',
          constructionSite: 'Барилгын талбай',
          parking: 'Зогсоол',
          mainEntrance: 'Үндсэн орц',
          street: 'Гудамж',
          balcony: 'Тагт',
          diningHallRoof: 'Зоогийн өрөөний<br/>дээвэр',
          officeRoof: 'Оффисын дээвэр',
          meetingHallEntrance: 'Уулзалтын<br/>танхимын орц',
          garageRoof: 'Гаражийн дээвэр',
          dormsRoof: 'Дотуур байрны<br/>дээвэр',
          meetingHallRoof: 'Уулзалтын<br/>танхимын<br/>дээвэр',
          supplyCloset: 'Хангамжийн<br/>шүүгээ'
        },
        plane: {
          spawnOfficialEntrance: 'Албаны орц',
          spawnReporterEntrance: 'Хэвлэлийн орц',
          spawnServiceEntrance: 'Үйлчилгээний орц',
          pressBathroom: 'Хэв.БЗ',
          meetingRoom: 'Уулзалтын өрөө',
          frontHallway: 'Урд<br/>коридор',
          executiveOffice: 'Удирдах<br/>оффис',
          mainEntrance: 'Гол орц',
          frontStairs: 'Урд шат',
          pantry: 'Зоорь',
          kitchen: 'Гал зуух',
          executiveHallway: 'Удирдахын коридор',
          executiveBedroom: 'Удирдахын<br/>унтлагын<br/>өрөө',
          changeRoom: 'Хувцас<br/>солих<br/>өрөө',
          laund: 'Угаалга',
          frontServiceEntrance: 'Үйлчилгээний<br/>урд хаалга',
          rightWing: 'Баруун жигүүр',
          backServiceEntrance: 'Үйлчилгээний<br/>арын хаалга',
          reporterEntrance: 'Хэвлэлийн орц',
          leftWing: 'Зүүн жигүүр',
          staffSection: 'Арын алба',
          securityRoom: 'Аюулгүй<br/>байдлын<br/>өрөө',
          pressSectionA: 'Хэвлэлийн<br/>хэсэг A',
          pressSectionB: 'Хэвлэлийн<br/>хэсэг B',
          backStairs: 'Арын шат',
          cargoHold: 'Ачааны хэсэг',
          serviceCorridor: 'Үйлчилгээний коридор',
          storage: 'Агуулах',
          luggageHold: 'Гар тээшийн<br/>хэсэг',
          firstAidStation: 'Анхны тусламжийн<br/>хэсэг',
          cargoFrontEntrance: 'Ачааны<br/>урд хаалга',
          cockpitStairs: 'Бүхээгийн шат',
          cabinStaff: 'Бүхээгийн<br/>баг',
          radioCabin: 'Радио',
          cabin: 'Бүхээг',
          caterer: 'Хүнс',
          serverRoomA: 'Серверийн өрөө A',
          serverRoomB: 'Серверийн өрөө B',
          technicalSeating: 'Техникийн суудал',
          ladderRoom: 'Шаттай<br/>өрөө'
        },
        skyscraper: {
          helipad: 'Helipad',
          tower: 'Tower',
          ventilationUnits: 'Ventilation Units',
          kitchen: 'Kitchen',
          pantry: 'Pantry',
          deliveryRoom: 'Delivery<br/>Room',
          houseLobby: 'House Lobby',
          houseEntrance: 'House<br/>Entrance',
          mainEntrance: 'Main<br/>Entrance',
          reception: 'Reception',
          bedroom: 'Bedroom',
          closet: 'Closet',
          bathroom: 'Bathroom',
          houseStairs: 'House<br/>Stairs',
          restaurant: 'Restaurant',
          toilet: 'Toilet',
          bbq: 'BBQ',
          backHallway: 'Back Hallway',
          mainStairs: 'Main<br/>Stairs',
          geishaRoom: 'Geisha<br/>Room',
          hallway: 'Hallway',
          karaoke: 'Karaoke',
          teaRoom: 'Tea Room',
          taiko: 'Taiko',
          terrace: 'Terrace',
          backStairs: 'Back<br/>Stairs',
          houseBalcony: 'House<br/>Balcony',
          exhibition: 'Exhibition',
          lounge: 'Lounge',
          workOffice: 'Work<br/>Office',
          clearance: 'Clearance',
          peacefullTree: 'Peacefull<br/>Tree',
          contemplationGarden: 'Contemplation<br/>Garden',
          westGarden: 'West<br/>Garden',
          bridge: 'Bridge',
          gazeebo: 'Gazeebo',
          restBalcony: 'Rest.<br/>Balcony',
          northGarden: 'North<br/>Garden',
          eastGarden: 'East<br/>Garden',
          sandGarden: 'Sand<br/>Garden',
          sidePath: 'Side<br/>Path',
          sideStairs: 'Side<br/>Stairs',
          dragonStatue: 'Dragon<br/>Statue',
          coveredWalkway: 'Covered<br/>Walkway'
        },
        yacht: {
          spawnSubmarine: 'Submarine',
          spawnZodiak: 'Zodiak',
          spawnSnowMobile: 'Snow Mobile',
          mapsRoom: 'Maps Room',
          cockpit: 'Cockpit',
          cockpitHallway: 'Cockpit Hallway',
          captainsOffice: 'Captain\'s<br/>Office',
          cockpitBalcony: 'Cockpit<br/>Balcony',
          topDeckStairs: 'Top<br/>Deck<br/>Stairs',
          helipadEntrance: 'Helipad<br/>Entrance',
          helipad: 'Helipad',
          spaDeck: 'Spa<br/>Deck',
          eastDeck: 'East Deck',
          westDeck: 'West Deck',
          frontDeck: 'Front<br/>Deck',
          masterBedroom: 'Master<br/>Bedroom',
          casino: 'Casino',
          pokerRoom: 'Poker<br/>Room',
          bathroom: 'Bath-<br/>room',
          bedroomHallway: 'Bedroom Hallway',
          casinoHallway: 'Casino Hallway',
          globeHallway: 'Globe<br/>Hallway',
          lounge: 'Lounge',
          cafeteria: 'Cafeteria',
          engine: 'Engine',
          backEntrance: 'Back<br/>Entrance',
          rearDeck: 'Rear<br/>Deck',
          serverRoom: 'Server<br/>Room',
          engineStorage: 'Engine<br/>Storage',
          engineControl: 'Engine<br/>Control',
          backStairs: 'Back<br/>Stairs',
          emergencyExit: 'Emergency Exit',
          engineHallway: 'Engine Hallway',
          frontStairs: 'Front<br/>Stairs',
          kitchen: 'Kitchen',
          staffDormitory: 'Staff<br/>Dormitory',
          westBalcony: 'West Balcony',
          eastBalcony: 'East Balcony',
          kitchenHallway: 'Kitchen Hallway',
          kitchenStairs: 'Kitchen Stairs',
          kitchenPantry: 'Kitchen<br/>Pantry',
          infirmary: 'Infirmary',
          borealSubRoom: 'Boreal Sub<br/>Room',
          cafeteriaHallway: 'Cafeteria Hallway',
          engineUtility: 'Engine<br/>Utility',
          submarine: 'Submarine',
          westGlacier: 'West Glacier',
          eastHullBreach: 'East Hull<br/>Breach',
          eastGlacier: 'East Glacier',
          frozenRiver: 'Frozen River',
          zodiac: 'Zodiac',
          westHullBreach: 'West Hull Breach',
          kingOfTheWorld: 'King of<br/>the World',
          roof: 'Roof',
          anchorName: 'Anchor',
          aklarkSubEntrance: 'Aklark Sub<br/>Entrance'
        }
      }
    };

  R6MapsLangTerms.registerLanguage(name, terms);

  return  {
    name: name,
    terms: terms
  };
})(R6MapsLangTerms);
