'use strict';

var R6MapsCommonLangTermsPolish = (function(R6MapsCommonLangTerms, undefined) {
  var name = 'pl',
    terms = {
      general: {
        pageTitleSelectMap: 'R6Maps.com - Wybierz mapę',
        pageTitleStart: '',
        cameraViewCaption: '{floorName} Widok z kamery',
        shortcutTip: 'Skrót: {shortcut}',
        menu: 'Menu',
        about: 'O R6Maps',
        languageHeader: 'Język',
        optionsHeader: 'Opcje',
        labelLosOpacity: 'Przeźroczystość granicy widoku z kamery',
        labelPercent: '{int}%',
        labelLosDefault: '(Domyślne)',
        labelLos105: 'Hę?',
        labelLos110: 'Absurd!',
        labelRoomLabelStyle: 'Styl wyświetlania nazw pomieszczeń',
        labelNumberFloorsToDisplay: 'Liczba wyświetlanych pięter',
        lockPanning: 'Zablokuj obrót',
        lockZooming: 'Zablokuj przybliżenie',
        fullScreen: 'Tryb pełnoekranowy',
        enableScreenshots: 'Włącz screenshoty',
        contributions: 'Wkład',
        supportSiteNote: 'Proszę, rozważ okazanie nam wsparcia za pomocą małej dotacji. :)',
        donateImg: 'https://www.paypalobjects.com/pl_PL/PL/i/btn/btn_donate_LG.gif'
      },
      roomLabelStyles: {
        Dark: 'Ciemny',
        Light: 'Jasny',
        DarkAndLarge: 'Duży i ciemny',
        LightAndLarge: 'Duży i jasny',
        DarkAndSmall: 'Mały i ciemny',
        LightAndSmall: 'Mały i jasny',
        DisplayNone: 'Wyłącz'
      },
      floorDisplayOptions: {
        one: '1 - Pełny',
        two: '2 - Podzielony',
        four: '3 - Podzielony (kratka)'
      },
      selectMaps: {
        selectAMap: 'Wybierz mapę',
        homeLink: 'Wybierz mapę'
      },
      compass: {
        letterN: 'Pn.',
        letterE: 'Wsch.',
        letterS: 'Pd.',
        letterW: 'Zach.'
      },
      floorNames: {
        basement: { full: 'Piwnica (-1)', short: '-1' },
        firstFloor: { full: 'Parter', short: '0' },
        secondFloor: { full: '1. Piętro', short: '1' },
        thirdFloor: { full: '2. Piętro', short: '2' },
        fourthFloor: { full: '3. Piętro', short: '3' },
        roof: { full: 'Dach', short: 'D' }
      },
      objectives: {
        bombShortA: 'A',
        bombShortB: 'B',
        bomb: 'Bomba',
        hostageShort: 'Za.',
        hostage: 'Zakładnik',
        secureShort: 'Z.t.',
        secure: 'Zabezpieczanie terenu',
        showAll: 'Pokaż wszystko'
      },
      legend: {
        breakableWalls: 'Zniszczalne ściany',
        breakableFloorTraps: 'Zniszczalne włazy',
        ceilingHatches: 'Właz sufitowy',
        lineOfSightWalls: 'Pole widzenia ścian',
        lineOfSightFloors: 'Pole widzenia podłóg',
        droneTunnels: 'Tunele dla dronów',
        objectives: 'Cele',
        insertionPoints: 'Punkt odrodzenia',
        securityCameras: 'Kamery bezpieczeństwa',
        skylights: 'Świetliki',
        onFloorAboveOrBelow: 'Piętro niżej lub wyżej',
        cameraLineOfSight: 'Pole widzenia kamery',
        ladders: 'Drabiny'
      },
      spawnPoints: {
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        e: 'E'
      },
      mapNames: {
        bank: 'Bank',
        bartlett: 'Uniw. Bartlett',
        border: 'Granica',
        chalet: 'Domek górski',
        club: 'Klub',
        coastline: 'Wybrzeże',
        consulate: 'Konsulat',
        favela: 'Fawele',
        hereford: 'Baza Hereford',
        house: 'Dom',
        kanal: 'Kanał',
        kafe: 'Kafe Dostojewski',
        oregon: 'Oregon',
        plane: 'Samolot prezydencki',
        skyscraper: 'Wieżowiec',
        yacht: 'Jacht'
      },
      mapRooms: {
        bank: {
          spawnBoulevard: 'Parking',
          spawnBackAlley: 'Dojście od alejki',
          printerRoom: 'Pokój<br/>z drukarkami',
          parkingLot: 'Parking - front',
          boulevard: 'Bulwar',
          jewelryFront: 'Jubiler',
          plaza: 'Plac',
          mainEntrance: 'Główne<br/>wejście',
          garageRamp: 'Rampa<br/>podjazdowa',
          exteriorParking: 'Parking<br/>zewnętrzny',
          garageRoof: 'Dach garażu',
          alleyAccess: 'Dojście<br/>od alejki',
          backAlleyRooftop: 'Dach nad<br/>tylną alejką',
          backAlley: 'Tylna alejka',
          highRoof: 'Wyższy dach',
          lowRoof: 'Niższy dach',
          vault: 'Skarbiec',
          goldVault: 'Skarbiec<br/>ze złotem',
          serverRoomStairs: 'Serwerownia<br/>schody',
          serverRoom: 'Serwerownia',
          CCTVRoom: 'Pokój ochrony',
          loadingDock: 'Rampa<br/>załadunkowa',
          secureHallway: 'Bezpieczny<br/>korytarz',
          sewer: 'Kanały',
          lockers: 'Szatnia',
          vaultLobby: 'Hol skarbca',
          vaultEntrance: 'Wejście<br/>do skarbca',
          mainStairway: 'Schody główne',
          bankGarage: 'Garaż',
          elevators: 'Windy',
          tellersOffice: 'Biuro<br/>kasjerów',
          archives: 'Archiwa',
          tellers: 'Kasy',
          loanOffice: 'Dział kredytów',
          officeHallway: 'Biuro korytarz',
          skylightStairwell: 'Schody ze<br/>świetlikiem',
          lobby: 'Hol',
          openArea: 'Strefia biurowa',
          staffRoom: 'Pokój obsługi',
          electricalRoom: 'Rodzielnia<br/>elektryczna',
          adminOffice: 'Biuro<br/>administratora',
          ATMs: 'Bankomaty',
          executiveHallway: 'Prywatny korytarz',
          frontDesk: 'Recepcja',
          executiveLounge: 'Sala zarządu',
          CEOOffice: 'Biuro prezesa',
          janitorCloset: 'Schowek<br/>sprzątaczy',
          hallway: 'Hol',
          terrace: 'Taras',
          stockTradingRoom: 'Pokój<br/>giełdowy',
          conferenceRoom: 'Sala<br/>konferencyjna'
        },
        bartlett: {
          archwayHall: 'Sala kolumnowa',
          backAlley: 'Tylnia aleja',
          bathroom: 'Łazienka',
          campusField: 'Pole<br/>kampusowe',
          classroom: 'Klasa',
          coatRoom: 'Szatnia',
          compassHallway: 'Korytarz',
          courtyard: 'Podwórze',
          centralHallway: 'Główny korytarz',
          diningRoom: 'Jadalnia',
          eastBalcony: 'Wschodni balkon<br/>(niewidoczny)',
          eastCorridor: 'Korytarz<br/>wschodni',
          eastStairs: 'Schody<br/>wschodnie',
          festival: 'Pole<br/>festiwalowe',
          frontEntrance: 'Wejście główne',
          frontOffice: 'Recepcja',
          frontPatio: 'Frontowe patio',
          gardenPass: 'Przejście<br/>przez<br/>ogród',
          kitchen: 'Kuchnia',
          lobby: 'Hol',
          lounge: 'Salon',
          lowerLibrary: 'Dolna<br/>biblioteka',
          mainGate: 'Główna brama',
          mainOffice: 'Biuro główne',
          modelHall: 'Sala<br/>modeli',
          pantry: 'Spiżarnia',
          parking: 'Parking',
          pianoRoom: 'Pokój muzyczny',
          readingRoom: 'Czytelnia',
          roof: 'Dach',
          rowingMuseum: 'Muzeum<br/>wioślarstwa',
          serviceRoom: 'Pomieszczenie<br/>techniczne',
          terrace: 'Taras',
          trophyRoom: 'Sala trofeów',
          upperLibrary: 'Górna<br/>biblioteka',
          vistaHallway: 'Korytarz<br/>za<br/>schodami',
          westBalcony: 'Zachodni balkon<br/>(niewidoczny)',
          westCorridor: 'Korytarz<br/>zachodni'
        },
        border: {
          armoryLockers: 'Szafki<br/>w zbrojowni',
          tellers: 'Stanowiska<br/>obsługi',
          ventilationRoom: 'Pomiesz-<br/>czenie<br/>wentyla-<br/>cyjne',
          exitHallway: 'Korytarz do<br/>wyjścia',
          supplyCorridor: 'Korytarz<br/>techniczny',
          detention: 'Areszt',
          customsInspection: 'Kontrola celna',
          customsDesk: 'Biuro<br/>celne',
          centralStairs: 'Główne schody',
          serverRoom: 'Serwerownia',
          supplyRoom: 'Schowek',
          workshop: 'War-<br/>sztat',
          mainLobby: 'Główne<br/>lobby',
          bathroom: 'Łazienka',
          waitingRoom: 'Poczekalnia',
          eastStairs: 'Wschodnie<br/>schody',
          passportCheck: 'Kontrola<br/>paszportowa',
          archives: 'Archiwa',
          offices: 'Biura',
          officesHallway: 'Korytarz<br/>w biurze',
          fountain: 'Fontanna',
          mainHallway: 'Główny<br/>korytarz',
          armoryDesk: 'Administracja<br/>zbrojowni',
          securityRoom: 'Pokój<br/>ochrony',
          breakRoom: 'Pokój<br/>socjalny',
          spawnEastVehicleEntrance: 'Wjazd od wschodu',
          spawnValley: 'Dolina',
          spawnWestVehicleExit: 'Wyjazd od zachodu',
          westTower: 'Zachodnia<br/>wieża',
          pedestrianExit: 'Wyjście<br/>dla pieszych',
          valley: 'Dolina',
          parkingLotEntrance: 'Wjazd<br/>na parking',
          parkingLot: 'Parking',
          westRoad: 'Droga zachodnia',
          vehicleCustoms: 'Kontrola<br/>pojazdów',
          crashScene: 'Miejsce<br/>wypadku',
          eastRoad: 'Wjazd<br/>od wschodu',
          pedestrianEntrance: 'Wejście<br/>dla pieszych',
          pedestrianCustoms: 'Kontrola<br/>pieszych',
          watchTower: 'Strażnica',
          eastAlley: 'Wschodnia<br/>alejka',
          parkingLotAlley: 'Aleja<br/>parking',
          northBalcony: 'Północny balkon',
          eastBalcony: 'Wschodni<br/>balkon',
          westBalcony: 'Zachodni<br/>balkon',
          southBalcony: 'Południowy balkon',
          roof: 'Dach'
        },
        coastline: {
          aquarium: 'Akwarium',
          backAlley: 'Tylna<br/>alejka',
          balcony: 'Balkon',
          bathroom: 'Łazienka',
          billiardsRoom: 'Sala<br/>bilardowa',
          blueBar: 'Blue bar',
          cantina: 'Bufet',
          courtyard: 'Dziedziniec',
          djBooth: 'Stanowisko DJ(niewidoczne)',
          garageRoof: 'Dach garażu',
          hallOfFame: 'Sala sławy',
          hallway: 'Korytarz',
          hookahDeck: 'Taras dla palących<br/>(niewidoczny)',
          hookahLounge: 'Pralnia',
          kitchen: 'Kuchnia',
          mainEntrance: 'Główne<br/>wejście',
          mainLobby: 'Główne lobby',
          northStairs: 'Północne<br/>schody',
          office: 'Biuro',
          penthouse: 'Apartament',
          pool: 'Basen',
          poolEntrance: 'Wejście<br/>na basen',
          poolSide: 'Chodnik<br/>przy basenie',
          rooftop: 'Dach',
          ruins: 'Ruiny',
          securityRoom: 'Pomieszczenie<br/>ochrony',
          serviceEntrance: 'Wejście<br/>serwisowe',
          southHallway: 'Południowy<br/>korytarz',
          southPromenade: 'Południowa promenada',
          southStairs: 'Południowe<br/>schody',
          sunriseBar: 'Sunrise bar',
          sunRoom: 'Pokój<br/>widokowy',
          theater: 'Sala wideo',
          terrace: 'Taras',
          toilets: 'Toalety',
          vipLounge: 'Salon dla<br/>VIP-ów',
          walkway: 'Chodnik'
        },
        chalet: {
          spawnFrontYard: 'Frontowe podwórze',
          spawnCampfire: 'Ognisko Las',
          spawnCliffside: 'Klif',
          spawnLakeside: 'Jezioro',
          libraryStairs: 'Biblioteka<br/>schody',
          snowmobileGarageCorridor: 'Garaż skuterów korytarz',
          snowmobileGarage: 'Garaż<br/>skuterów',
          greatRoomStairs: 'Salon<br/>schody',
          storageRoom: 'Magazyn',
          wineCellar: 'Piwnica<br/>z winem',
          wineStock: 'Zapas<br/>wina',
          basementHallway: 'Korytarz',
          backyardStairs: 'Tylne<br/>podwórze<br/>schody',
          mainStairs: 'Główne<br/>schody',
          mainGarage: 'Główny garaż',
          garageEntrance: 'Główny garaż<br/>wiazd',
          westEntrance: 'Wejście<br/>zachodnie',
          gamingRoomHallway: 'Pokój gier<br/>korytarz',
          gamingRoom: 'Pokój gier',
          bar: 'Bar',
          greatRoom: 'Salon',
          diningRoom: 'Jadalnia',
          mainEntrance: 'Główne<br/>wejście',
          trophyRoom: 'Pokój myśliwski',
          kitchenHallway: 'Kuchnia<br/>korytarz',
          kitchen: 'Kuchnia',
          libraryHallway: 'Biblioteka korytarz',
          libraryEntrance: 'Biblioteka<br/>wejście',
          library: 'Biblioteka',
          bedroomTerrace: 'Sypialnia<br/>taras',
          fireplaceHallway: 'Kominek<br/>korytarz',
          bedroomHallway: 'Sypialnia<br/>korytarz',
          masterBathroom: 'Główna<br/>łazienka',
          masterBedroom: 'Główna sypialnia',
          office: 'Biuro',
          woodenTrail: 'Leśna ścieżka',
          campfireWood: 'Ognisko Las',
          backyard: 'Tylne podwórze',
          gazeebo: 'Altana',
          cliffsideStairs: 'Schody<br/>na klifie',
          cliffsideWoods: 'Las<br/>na klifie',
          backyardPatio: 'Tylne patio',
          officeBalcony: 'Biuro<br/>balkon',
          helipadTrail: 'Droga<br/>do lądowiska',
          helipad: 'Lądowisko<br/>dla śmigłowców',
          frontYardPatio: 'Frontowe patio',
          frontYard: 'Frontowe podwórze',
          bathroomBalcony: 'Balkon w<br/>łazience',
          libraryBalcony: 'Balkon w<br/>bibliotece',
          bedroomBalcony: 'Balkon w<br/>sypialni',
          snowmobiles: 'Skutery śnieżne'
        },
        club: {
          spawnMainEntrance: 'Główne wejście',
          spawnShippingDocks: 'Platforma załadunkowa',
          spawnWarehouse: 'Magazyn',
          spawnConstructionSite: 'Plac budowy',
          easternSubroof: 'Dolny dach<br/>Wschód',
          constructionSite: 'Plac budowy',
          container: 'Kontener',
          graffitiArea: 'Teren przy graffiti',
          recreationArea: 'Teren<br/>rekreacyjny',
          junkyard: 'Śmietnik',
          VIPParking: 'Parking<br/>dla VIP-ów',
          mainGate: 'Główna brama',
          parking: 'Parking',
          kennels: 'Zagrody<br/>dla psów',
          trash: 'Śmieci',
          centralSubroof: 'Dolny dach<br/>Środek',
          easternRoof: 'Wschodni<br/>dach',
          centralRoof: 'Główny<br/>dach',
          westernRoof: 'Zachodni<br/>dach',
          balcony: 'Balkon',
          escapeTunnel: 'Tunel<br/>ewakuacyjny',
          arsenalRoom: 'Zbrojownia',
          basementHallway: 'Korytarz',
          memorialRoom: 'Sala<br/>z pamiątkami',
          utilityRoom: 'Pomieszczenie<br/>techniczne',
          oilPit: 'Kanał<br/>naprawczy',
          centralStairs: 'Główne<br/>schody',
          church: 'Kaplica',
          frontPorch: 'Frontowa weranda',
          garage: 'Garaż',
          lobby: 'Hol',
          stockRoom: 'Pokój<br/>z zapasami',
          garageStorage: 'Garaż<br/>składzik',
          lounge: 'Salon',
          bar: 'Bar',
          centralHallway: 'Główny korytarz',
          kitchen: 'Kuchnia',
          kitchenEntrance: 'Wejście<br/>kuchenne',
          westernHallway: 'Zachodni<br/>korytarz',
          stripClub: 'Klub<br/>ze striptizem',
          junkyardEntrance: 'Wejście<br/>od śmietnika',
          sideEntrance: 'Boczne wejście',
          changingRoom: 'Szatnia',
          bedroom: 'Sypialnia',
          bathroom: 'Łazienka',
          bedroomHallway: 'Sypialnia korytarz',
          logisticOffice: 'Biuro<br/>logistyczne',
          gym: 'Siłownia',
          secretStash: 'Tajna<br/>kryjówka',
          CCTVRoom: 'Pokój ochrony',
          cashRoom: 'Pokój<br/>z gotówką',
          easternStairs: 'Wschodnie<br/>schody'
        },
        consulate: {
          spawnRiotBarricade: 'Barykada',
          spawnPoliceLine: 'Strefa policyjna',
          spawnGasStation: 'Stacja benzynowa',
          spawnSideEntrance: 'Wejście boczne',
          exitStairs: 'Schody<br/>wyjściowe',
          garage: 'Garaż',
          basementCorridor: 'Korytarz piwnica',
          securityRoom: 'Pokój ochrony',
          cafeteria: 'Kafeteria',
          mainStairs: 'Schody główne',
          lockerHallway: 'Korytarz<br/>szafki',
          serviceStairs: 'Schody<br/>dla personelu',
          electricRoom: 'Rozdzielnia<br/>elektryczna',
          storageRoom: 'Magazyn',
          archives: 'Archiwa',
          archivesCorridor: 'Archiwa korytarz',
          pressRoom: 'Pokój prasowy',
          westCorridor: 'Korytarz zachodni',
          publicBathroom: 'Toalety<br/>publiczne',
          antechamber: 'Przedsionek',
          lobby: 'Hol',
          eastCorridor: 'Korytarz<br/>wschodni',
          tellers: 'Obsługa',
          visaOffice: 'Biuro wizowe',
          visaEntrance: 'Wejście do<br/>biura wizowego',
          frontDoor: 'Główne<br/>wejście',
          balcony: 'Balkon',
          copyRoom: 'Pokój ksero',
          cabinet: 'Gabinet',
          administrationOffice: 'Biuro<br/>administracji',
          breakRoom: 'Pokój<br/>socjalny',
          frontOffice: 'Recepcja',
          meetingRoom: 'Sala<br/>spotkań',
          hallway: 'Korytarz',
          consulFrontDesk: 'Recepcja<br/>konsulatu',
          privateBathroom: 'Prywatna<br/>łazienka',
          waitingRoom: 'Poczekalnia',
          consulateOffice: 'Biuro<br/>konsula',
          garageWay: 'Wjazd do garażu',
          courtyard: 'Podwórze',
          backCourtyard: 'Tylne podwórze',
          sideEntrance: 'Wejście boczne',
          dumpster: 'Śmietnik',
          parking: 'Parking',
          gardens: 'Ogrody',
          fountain: 'Fontanna',
          emergencyExit: 'Wyjście<br/>awaryjne',
          garageRoof: 'Dach<br/>garażu',
          memorialGarden: 'Ogród pamięci',
          policeLine: 'Strefa policyjna',
          riotBarracade: 'Barykada',
          eastFrontYard: 'Wschodnie podwórze',
          westFrontYard: 'Zachodnie podwórze',
          frontAlley: 'Frontowa aleja',
          buildingRoof: 'Dach budynku'
        },
        favela: {
          packagingRoom: 'Pakowalnia',
          footballApartment: 'Pokój futbolisty',
          armoryRoom: 'Zbrojownia',
          auntsApartment: 'Pokój<br/>ciotki',
          auntsBedroom: 'Sypialnia<br/>ciotki',
          growRoom: 'Uprawa',
          bikersApartment: 'Pokój<br/>motocyklisty',
          methLab: 'Laboratorium<br/>mety',
          footballBedroom: 'Sypialnia<br/>futbolisty',
          footballOffice: 'Biuro<br/>futbolisty',
          bikersBedroom: 'Sypialnia<br/>motocyklisty',
          backStairs: 'Tylne<br/>schody',
          auntsHall: 'Przedpokój<br/>ciotki',
          kidsRoom: 'Pokój<br/>dziecięcy',
          mainStairs: 'Główne schody',
          stairHall: 'Klatka<br/>scho-<br/>dowa',
          roof: 'Dach',
          laundryRoom: 'Pralnia',
          vaultRoom: 'Skarbiec',
          bikersGarage: 'Garaż<br/>motocyklisty',
          backAlley: 'Tylna alejka',
          schoolAlley: 'Alejka przy szkole',
          footballPitch: 'Miejsce do gry',
          market: 'Targ',
          marketAlley: 'Aleja<br/>targowa',
          schoolRooftops: 'Szkoła (dach)',
          street: 'Ulica',
          rooftops: 'Dachy',
          courtyard: 'Podwórze',
          accessAlley: 'Alejka jazdowa',
          shop: 'Sklep<br/>(niewidoczny)',
          marketRooftops: 'Targ (dach)'
        },
        hereford: {
          spawnTrainingCourse: 'Tor przeszkód',
          spawnParking: 'Parking',
          spawnShootingRange: 'Strzelnica',
          armory: 'Zbrojownia',
          lockers: 'Szatnia',
          corridor: 'Korytarz',
          mainStairs: 'Główne<br/>schody',
          maintenanceArea: 'Pomieszczenie<br/>techniczne',
          briefingRoom: 'Sala odpraw',
          basementEntrance: 'Wejście<br/>do piwnicy',
          garage: 'Garaż',
          TVRoom: 'Pokój TV',
          garageCorridor: 'Garaż korytarz',
          kitchen: 'Kuchnia',
          corridor1: 'Korytarz<br/>1',
          diningRoom: 'Jadalnia',
          pianoLounge: 'Pokój<br/>muzyczny',
          office: 'Gabinet',
          masterBedroom: 'Główna sypialnia',
          backAccess: 'Tylne<br/>wejście',
          laundryRoom: 'Pralnia',
          bathroom: 'Łazienka',
          kidsBedroom: 'Sypialnia<br/>dziecięca',
          ballisticMatDepot: 'Skład<br/>okładzin<br/>balistycznych',
          storage: 'Magazyn',
          storageCorridor: 'Magazyn<br/>korytarz',
          dummyDepot: 'Skład celów',
          workshop: 'Warsztat',
          shootingRangeEastEntrance: 'Strzelnica<br/>wejście od wsch.',
          shootingRangeWestEntrance: 'Strzelnica<br/>wejście od zach.',
          tireSetting: 'Tor z opon',
          observationRamp: 'Rampa obserwacyjna',
          barracks: 'Kwatery',
          busBackAlley: 'Tylna alejka<br/>autobus',
          rappelTower: 'Wieża<br/>wspinaczkowa',
          terrace: 'Taras',
          frontAccess: 'Frontowe wejście',
          chapelGate: 'Brama<br/>przed kaplicą',
          forkliftArea: 'Plac-<br/>wózki widłowe',
          sideStairsAlley: 'Alejka<br/>schody boczne',
          sideStairs: 'Schody<br/>boczne',
          garageTop: 'Dach garażu',
          rooftop: 'Dach',
          parkingEntrance: 'Wjazd na parking'
        },
        house: {
          spawnConstructionSite: 'Plac budowy',
          spawnRiverDocks: 'Pomost',
          spawnAPCArea: 'Strefa transportowa',
          spawnSideStreet: 'Boczna ulica',
          depot: 'Skład',
          trainingRoom: 'Sala ćwiczeń',
          kitchenStairs: 'Schody<br/>kuchenne',
          sideStairs: 'Schody<br/>boczne',
          laundryRoom: 'Pralnia',
          garage: 'Garaż',
          livingRoom: 'Salon',
          backEntrance: 'Tylne wejście',
          lobby: 'Hol',
          kitchen: 'Kuchnia',
          office: 'Gabinet',
          diningRoom: 'Jadalnia',
          workshop: 'Warsztat',
          kidsBedroom: 'Pokój<br/>dziecięcy',
          upperHallway: 'Główny<br/>korytarz',
          lobbyStairs: 'Schody<br/>w holu',
          walkIn: 'Garderoba',
          masterBedroom: 'Główna sypialnia',
          bathroom: 'Łazienka',
          sideStreet: 'Boczna ulica',
          garageEntrance: 'Wejście<br/>do garażu',
          garden: 'Ogród',
          backAlley: 'Tylna alejka',
          patio: 'Patio',
          jacuzzi: 'Jacuzzi',
          basementStairs: 'Schody<br/>do piwnicy',
          treehouseAlley: 'Alejka do domku<br/>na drzewie',
          frontYard: 'Podwórko',
          frontStreet: 'Ulica od frontu',
          frontPorch: 'Frontowa wyranda',
          backPorch: 'Tylna wyranda',
          backPorchTop: 'Tylna wyranda góra',
          frontPorchTop: 'Frontowa wyranda góra',
          rooftop: 'Dach'
        },
        kanal: {
          spawnFloatingDock: 'Pływający dok',
          spawnSailboats: 'Żaglówki',
          spawnConstructionSite: 'Plac budowy',
          boatGarage: 'Garaż na łodzie',
          boatSupplies: 'Pomieszczenie<br/>z osprzętem',
          pipes: 'Cieknące rury',
          boatSuppliesHallway: 'Pom.<br/>z osprzętem<br/>korytarz',
          lockerRoom: 'Szafki',
          coastGuardStairs: 'Straż<br/>przybrzeżna<br/>schody',
          showers: 'Natryski',
          showersCorridor: 'Natryski<br/>korytarz',
          loadingDock: 'Rampa załadunkowa',
          machineHallway: 'Maszynownia',
          controlCenterStairs: 'Sterownia<br/>schody',
          holdingRoom: 'Depozyt celny',
          holdingRoomHallway: 'Depozyt<br/>celny<br/>korytarz',
          radio: 'Radiostacja',
          coastGuardOffice: 'Straż przybrzeżna<br/>biuro',
          archives: 'Archiwa',
          coastGuardHall: 'Straż<br/>przybrzeżna<br/>korytarz',
          mainEntrance: 'Główne wejście',
          lounge: 'Salon',
          bridge: 'Most',
          modelRoom: 'Diorama',
          securityRoom: 'Pokój ochrony',
          projectorRoom: 'Pokój<br/>z projektorem',
          mapsOffice: 'Pokój z mapami',
          mapsOfficeHallway: 'Pokój z mapami<br/>korytarz',
          kitchen: 'Kuchnia',
          cafeteria: 'Stołówka',
          plantsHallway: 'Korytarz z roślinami',
          thirdFloorExit: 'Wyjście<br/>z 2 piętra',
          controlRoom: 'Posterunek<br/>dowodzenia',
          electricRoom: 'Rozdzielnia<br/>elektryczna',
          controlRoomHallway: 'Centrum kontroli korytarz',
          serverRoom: 'Serwerownia',
          lockgate: 'Śluza',
          quayContainers: 'Kontenery na nabrzeżu',
          lockgateTunnel: 'Tunel ze śluzą',
          waterWalkway: 'Kładka',
          quayConstruction: 'Plac budowy na nabrzeżu',
          constructionSite: 'Plac budowy',
          constructionEntrance: 'Wejście na<br/>plac budowy',
          parkingAlley: 'Droga na parking',
          parkingEntrance: 'Wjazd<br/>na parking',
          middleRoad: 'Droga<br/>przy łączniku',
          forkliftAlley: 'Alejka<br/>dla wózków<br/>widłowych',
          frontLawn: 'Frontowy trawnik',
          basementStairs: 'Schody do piwnicy',
          coastGuardRoof: 'Straż przybrzeżna<br/>dach',
          bridgeRoof: 'Dach mostu',
          roofBrickPile: 'Sterta cegieł<br/>na dachu',
          balcony: 'Balkon',
          controlCenterRoof: 'Posterunek dowodzenia<br/>dach',
          dockStairs: 'Schody do doków',
          parking: 'Parking',
          boatCrane: 'Dźwig do łodzi',
          mapArchives: 'Mapy<br/>archiwa'
        },
        kafe: {
          spawnRiverDocks: 'Pomost',
          spawnChristmasMarket: 'Jarmark świąteczny',
          spawnPark: 'Park',
          laundryRoom: 'Pralnia',
          frontStairs: 'Frontowe<br/>schody',
          bakery: 'Piekarnia',
          bakeryKitchen: 'Piekarnia<br/>kuchnia',
          kitchenPrep: 'Stanowisko<br/>kuchenne',
          kitchenGrill: 'Kuchnia gril',
          kitchenPickUp: 'Kuchnia<br/>odbiór',
          coldRoom: 'Chłodnia',
          diningRoom: 'Jadalnia',
          backStairs: 'Tylne<br/>schody',
          coldRoomCorridor: 'Chłodnia<br/>korytarz',
          VIPSection: 'Sekcja VIP',
          barStairs: 'Bar schody',
          storage: 'Magazyn',
          museumEntrance: 'Wejście do muzeum',
          miningRoom: 'Sala kopalniana',
          trainMuseum: 'Muzeum kolei',
          pillarDiningRoom: 'Jadalnia kolumnowa',
          mainCorridor: 'Główny<br/>korytarz',
          readingRoomCorridor: 'Czytelnia korytarz',
          readingRoom: 'Czytelnia',
          fireplaceHall: 'Sala<br/>kominkowa',
          cigarShop: 'Sklepik cygarowy',
          cigarLounge: 'Salonik cygarowy',
          bar: 'Bar',
          barBackstore: 'Bar<br/>zaplecze',
          washrooms: 'Toalety',
          washroomCorridor: 'Toalety korytarz',
          cocktailLounge: 'Bar<br/>koktajlowy',
          cocktailLoungeEntrance: 'Wejście<br/>do baru<br/>koktajlowego',
          westMainStreet: 'Główna ulica zachód',
          mainStreet: 'Główna ulica',
          eastMainStreet: 'Główna ulica wschód',
          bakeryParking: 'Parking<br/>przed piekarnią',
          bakeryRoof: 'Dach piekarni',
          cafeRoofTop: 'Dach kafeterii ',
          terrace: 'Taras',
          backAlley: 'Tylna aleja',
          garrage: 'Garaż',
          parkAlley: 'Aleja w parku'
        },
        oregon: {
          spawnJunkyard: 'Śmietnik',
          spawnStreet: 'Ulica',
          spawnConstructionSite: 'Plac budowy',
          towerStairs: 'Schody<br/>na wierze',
          boilerRoom: 'Kotłownia',
          electricRoom: 'Rozdzielnia<br/>elektryczna',
          bunkerEntrance: 'Wejście<br/>do bunkra',
          bunker: 'Bunkier',
          basementCorridor: 'Korytarz',
          supplyRoom: 'Schowek',
          laundryRoom: 'Pralnia',
          laundryStorage: 'Pralnia<br/>magazyn',
          laundryStairs: 'Pralnia<br/>schody',
          office: 'Biuro',
          diningHall: 'Stołówka',
          diningHallCorridor: 'Stołówka korytarz',
          showers: 'Prysznice',
          kitchen: 'Kuchnia',
          bathroom: 'Łazienka',
          dormStairs: 'Schody do<br/>głównej sypialni',
          pantry: 'Spiżarnia',
          bathroomCorridor: 'Łazienka korytarz',
          classroom: 'Klasa',
          lobby: 'Hol',
          mainStairs: 'Główne<br/>schody',
          meetingHall: 'Sala spotkań',
          rearStage: 'Kulisy',
          garage: 'Garaż',
          officeStorage: 'Biura skład',
          kidsDorm: 'Sypialnie dziecięce',
          dormMainHall: 'Sypialnie<br/>główny korytarz',
          smallDorms: 'Małe sypialnie',
          armoryCorridor: 'Zbrojownia<br/>korytarz',
          masterBedroom: 'Główna<br/>sypialnia',
          armory: 'Zbrojownia',
          walkIn: 'Garderoba',
          attic: 'Poddasze',
          watchTower: 'Wieża<br/>obserwacyjna',
          busYard: 'Zajezdnia',
          junkyard: 'Śmietnik',
          farmlands: 'Uprawy',
          shootingRange: 'Strzelnica',
          constructionSite: 'Plac budowy',
          parking: 'Parking',
          mainEntrance: 'Główne wejście',
          street: 'Ulica',
          balcony: 'Balkon',
          diningHallRoof: 'Dach<br/>nad jadalnią',
          officeRoof: 'Dach<br/>nad biurami',
          meetingHallEntrance: 'Sala spotkań<br/>wejście',
          garageRoof: 'Dach nad garażem',
          dormsRoof: 'Dach nad<br/>sypialniami',
          meetingHallRoof: 'Dach nad<br/>salą spotkań',
          supplyCloset: 'Spiżarnia'
        },
        plane: {
          spawnOfficialEntrance: 'Główne wejście',
          spawnReporterEntrance: 'Wejście dla reporterów',
          spawnServiceEntrance: 'Front. wej. dla personelu',
          pressBathroom: 'Łazienka<br/>dla prasy',
          meetingRoom: 'Sala<br/>konferencyjna',
          frontHallway: 'Przedni<br/>korytarz',
          executiveOffice: 'Gabinet',
          mainEntrance: 'Główne wejście',
          frontStairs: 'Przednie schody',
          pantry: 'Spiżarnia',
          kitchen: 'Kuchnia',
          executiveHallway: 'Korytarz',
          executiveBedroom: 'Główna<br/>sypialnia',
          changeRoom: 'Garderoba',
          laund: 'Pralnia',
          frontServiceEntrance: 'Frontowe wejście<br/>dla personelu',
          rightWing: 'Prawe skrzydło',
          backServiceEntrance: 'Tylne wejście<br/>dla personelu',
          reporterEntrance: 'Wejście<br/>dla reporterów',
          leftWing: 'Lewe skrzydło',
          staffSection: 'Sekcja<br/>dla personelu',
          securityRoom: 'Pokój ochrony',
          pressSectionA: 'Strefa prasowa A',
          pressSectionB: 'Strefa prasowa B',
          backStairs: 'Tylne schody',
          cargoHold: 'Ładownia',
          serviceCorridor: 'Korytarz<br/>techniczny',
          storage: 'Magazyn',
          luggageHold: 'Luk bagażowy',
          firstAidStation: 'Punkt pierwszej pomocy',
          cargoFrontEntrance: 'Ładownia<br/>Przednie wejście',
          cockpitStairs: 'Schody<br/>do kokpitu',
          cabinStaff: 'Personel<br/>pokładowy',
          radioCabin: 'Kabina radiowa',
          cabin: 'Kokpit',
          caterer: 'Catering',
          serverRoomA: 'Serwerownia A',
          serverRoomB: 'Serwerownia B',
          technicalSeating: 'Dział techniczny',
          ladderRoom: 'Pomieszczenie<br/>z drabiną'
        },
        skyscraper: {
          helipad: 'Lądowisko',
          tower: 'Wieża',
          ventilationUnits: 'Wentylatory',
          kitchen: 'Kuchnia',
          pantry: 'Spiżarnia',
          deliveryRoom: 'Pokój<br/>dostaw',
          houseLobby: 'Lobby',
          houseEntrance: 'Wejście<br/>do domu',
          mainEntrance: 'Główne<br/>wejście',
          reception: 'Recepcja',
          bedroom: 'Sypialnia',
          closet: 'Szafa',
          bathroom: 'Łazienka',
          houseStairs: 'Schody<br/>w domu',
          restaurant: 'Restauracja',
          toilet: 'Toaleta',
          bbq: 'Grill',
          backHallway: 'Tylny hol',
          mainStairs: 'Główne<br/>schody',
          geishaRoom: 'Pokój<br/>dla gejsz',
          hallway: 'Korytarz',
          karaoke: 'Karaoke',
          teaRoom: 'Herbaciarnia',
          taiko: 'Taiko',
          terrace: 'Taras',
          backStairs: 'Tylne<br/>schody',
          houseBalcony: 'Balkon<br/>domu',
          exhibition: 'Wystawa',
          lounge: 'Salon',
          workOffice: 'Biuro',
          clearance: 'Wejście<br/>dla VIP-ów',
          peacefullTree: 'Drzewo pokoju',
          contemplationGarden: 'Świątynia<br/>dumienia',
          westGarden: 'Zachodni<br/>ogród',
          bridge: 'Most',
          gazeebo: 'Altana',
          restBalcony: 'Balkon<br/>restauracji',
          northGarden: 'Północny<br/>ogród',
          eastGarden: 'Wschodni<br/>ogród',
          sandGarden: 'Ogród<br/>piaskowy',
          sidePath: 'Boczna<br/>ścieżka',
          sideStairs: 'Boczne<br/>schody',
          dragonStatue: 'Rzeźba<br/>smoka',
          coveredWalkway: 'Zadaszone<br/>przejście'
        },
        yacht: {
          spawnSubmarine: 'Łódź podwodna',
          spawnZodiak: 'Zodiak',
          spawnSnowMobile: 'Skuter śnieżny',
          mapsRoom: 'Pokój z mapami',
          cockpit: 'Kokpit',
          cockpitHallway: 'Kokpit korytarz',
          captainsOffice: 'Biuro kapitana',
          cockpitBalcony: 'Kokpit<br/>balkon',
          topDeckStairs: 'Schody<br/>na górny<br/>pokład',
          helipadEntrance: 'Wejście<br/>na lądowisko',
          helipad: 'Lądowisko',
          spaDeck: 'Pokład<br/>ze spa',
          eastDeck: 'Pokład wschodni',
          westDeck: 'Pokład zachodni',
          frontDeck: 'Przedni<br/>pokład',
          masterBedroom: 'Główna<br/>sypialnia',
          casino: 'Kasyno',
          pokerRoom: 'Sala<br/>do gry<br/>w pokera',
          bathroom: 'Łazienka',
          bedroomHallway: 'Łazienka korytarz',
          casinoHallway: 'Kasyno korytarz',
          globeHallway: 'Korytarz<br/>z globusem',
          lounge: 'Salon',
          cafeteria: 'Kafeteria',
          engine: 'Maszynownia',
          backEntrance: 'Maszynownia<br/>tylne wejście',
          rearDeck: 'Tylny<br/>pokład',
          serverRoom: 'Serwerownia',
          engineStorage: 'Maszynownia<br/>magazyn',
          engineControl: 'Maszynownia<br/>sterownia',
          backStairs: 'Tylne<br/>schody',
          emergencyExit: 'Wyjście ewakuacyjne',
          engineHallway: 'Maszynownia korytarz',
          frontStairs: 'Schody<br/>frontowe',
          kitchen: 'Kuchnia',
          staffDormitory: 'Sypialnia<br/>załogi',
          westBalcony: 'Zachodni balkon',
          eastBalcony: 'Wschodni balkon',
          kitchenHallway: 'Kuchania korytarz',
          kitchenStairs: 'Kuchnia schody',
          kitchenPantry: 'Kuchnia<br/>spiżarnia',
          infirmary: 'Lazaret',
          borealSubRoom: 'Aklark<br/>łódź podwodna',
          cafeteriaHallway: 'Kafeteria korytarz',
          engineUtility: 'Maszynownia<br/>panele',
          submarine: 'Łódź podwodna',
          westGlacier: 'Lodowiec zachodni ',
          eastHullBreach: 'Wyłom<br/>wschodni',
          eastGlacier: 'Lodowiec wschodni',
          frozenRiver: 'Zamarznięta rzeka',
          zodiac: 'Ponton',
          westHullBreach: 'Wyłom zachodni',
          kingOfTheWorld: 'Władca<br/>świata',
          roof: 'Dach',
          anchorName: 'Kotwica',
          aklarkSubEntrance: 'Aklark<br/>łódź podwodna<br/>wejście'
        }
      }
    };

  R6MapsCommonLangTerms.registerLanguage(name, terms);

  return  {
    name: name,
    terms: terms
  };
})(R6MapsCommonLangTerms);
